services:
  api:
    container_name: api
    ports:
      - ${API_PORT}:${API_PORT}
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: ./apps/api/.env
    depends_on:
      - api_db
      - redis
      - history_ms
      - recommendation_ms

  history_ms:
    container_name: history_ms
    ports:
      - ${HISTORY_MS_PORT}:${HISTORY_MS_PORT}
    build:
      context: .
      dockerfile: apps/history_ms/Dockerfile
    env_file: ./apps/history_ms/.env
    depends_on:
      - history_db

  recommendation_ms:
    container_name: recommendation_ms
    ports:
      - ${RECOMMENDATION_MS_PORT}:${RECOMMENDATION_MS_PORT}
    build:
      context: .
      dockerfile: apps/recommendation_ms/Dockerfile
    env_file: ./apps/recommendation_ms/.env
    depends_on:
      - recommendation_db
      - history_ms

include:
  - path: ./stores-compose.yml
