package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"errors"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/apperror"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/shared"
	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (uuid.UUID, error) {
	user, err := r.AuthService.Login(ctx, input)
	if err != nil {
		var validationErr *apperror.ValidationError
		if errors.As(err, &validationErr) {
			return uuid.Nil, r.handleError(err)
		}

		return uuid.Nil, ErrInvalidEmailOrPassword
	}

	err = r.Sessions.RenewToken(ctx)
	if err != nil {
		return uuid.Nil, r.handleError(err)
	}

	r.Sessions.Put(ctx, shared.SessionUserIDKey, user.ID)
	r.Sessions.Put(ctx, shared.SessionRoleIDKey, user.RoleID)

	return user.ID, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (string, error) {
	if !r.Sessions.Exists(ctx, shared.SessionUserIDKey) {
		return "", ErrUserNotLoggedIn
	}

	if err := r.Sessions.Destroy(ctx); err != nil {
		return "", r.handleError(err)
	}

	return "user successfully logged out", nil
}
