package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/generated"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// Reviews is the resolver for the reviews field.
func (r *contentResolver) Reviews(ctx context.Context, obj *model.Content) ([]*model.Review, error) {
	reviews, err := r.ReviewService.ListReviewsByMovie(ctx, obj.ID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return reviews, nil
}

// Episodes is the resolver for the episodes field.
func (r *contentResolver) Episodes(ctx context.Context, obj *model.Content) ([]*model.Episode, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	reviews, err := r.EpisodeService.ListEpisodesBySeries(ctx, obj.ID, profileID, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return reviews, nil
}

// CreateContent is the resolver for the createContent field.
func (r *mutationResolver) CreateContent(ctx context.Context, input model.CreateContentInput) (uuid.UUID, error) {
	contentID, err := r.ContentService.CreateContent(ctx, input)
	if err != nil {
		return uuid.Nil, r.handleError(err)
	}

	return contentID, nil
}

// UpdateContent is the resolver for the updateContent field.
func (r *mutationResolver) UpdateContent(ctx context.Context, id uuid.UUID, input model.UpdateContentInput) (*model.Content, error) {
	updatedContent, err := r.ContentService.UpdateContent(ctx, id, input)
	if err != nil {
		return nil, r.handleError(err)
	}

	return updatedContent, nil
}

// DeleteContent is the resolver for the deleteContent field.
func (r *mutationResolver) DeleteContent(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.ContentService.DeleteContent(ctx, id)
	if err != nil {
		return false, r.handleError(err)
	}

	return true, nil
}

// GetContent is the resolver for the getContent field.
func (r *queryResolver) GetContent(ctx context.Context, id uuid.UUID) (*model.Content, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	content, err := r.ContentService.GetContent(ctx, id, profileID, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return content, nil
}

// ListContents is the resolver for the listContents field.
func (r *queryResolver) ListContents(ctx context.Context) ([]*model.Content, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	contents, err := r.ContentService.ListContents(ctx, profileID, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return contents, nil
}

// ListContentsByType is the resolver for the listContentsByType field.
func (r *queryResolver) ListContentsByType(ctx context.Context, contentType model.ContentType) ([]*model.Content, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	contents, err := r.ContentService.ListContentsByType(ctx, profileID, userID, contentType)
	if err != nil {
		return nil, r.handleError(err)
	}

	return contents, nil
}

// ListContentsByGenre is the resolver for the listContentsByGenre field.
func (r *queryResolver) ListContentsByGenre(ctx context.Context, genreID int32) ([]*model.Content, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	contents, err := r.ContentService.ListContentsByGenre(ctx, profileID, userID, genreID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return contents, nil
}

// Content returns generated.ContentResolver implementation.
func (r *Resolver) Content() generated.ContentResolver { return &contentResolver{r} }

type contentResolver struct{ *Resolver }
