package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// MovieReviews is the resolver for the movieReviews field.
func (r *contentResolver) MovieReviews(ctx context.Context, obj *model.Content) ([]*model.Review, error) {
	reviews, err := r.ReviewService.ListReviewsByMovie(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("failed to list reviews", slog.Any("error", err))
		return nil, handleError(err)
	}

	return reviews, nil
}

// Episodes is the resolver for the episodes field.
func (r *contentResolver) Episodes(ctx context.Context, obj *model.Content) ([]*model.Episode, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to list episodes", slog.Any("error", err))
		return nil, handleError(err)
	}

	reviews, err := r.EpisodeService.ListEpisodesBySeries(ctx, obj.ID, profileID)
	if err != nil {
		r.Logger.Error("failed to list reviews", slog.Any("error", err))
		return nil, handleError(err)
	}

	return reviews, nil
}

// CreateContent is the resolver for the createContent field.
func (r *mutationResolver) CreateContent(ctx context.Context, input model.CreateContentInput) (*model.Content, error) {
	panic(fmt.Errorf("not implemented: CreateContent - createContent"))
}

// UpdateContent is the resolver for the updateContent field.
func (r *mutationResolver) UpdateContent(ctx context.Context, id uuid.UUID, input model.UpdateContentInput) (*model.Content, error) {
	panic(fmt.Errorf("not implemented: UpdateContent - updateContent"))
}

// DeleteContent is the resolver for the deleteContent field.
func (r *mutationResolver) DeleteContent(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteContent - deleteContent"))
}

// ListContents is the resolver for the listContents field.
func (r *queryResolver) ListContents(ctx context.Context) ([]*model.Content, error) {
	panic(fmt.Errorf("not implemented: ListContents - listContents"))
}

// ListKidsContents is the resolver for the listKidsContents field.
func (r *queryResolver) ListKidsContents(ctx context.Context) ([]*model.Content, error) {
	panic(fmt.Errorf("not implemented: ListKidsContents - listKidsContents"))
}

// ListContentsByType is the resolver for the listContentsByType field.
func (r *queryResolver) ListContentsByType(ctx context.Context, contentType model.ContentType) ([]*model.Content, error) {
	panic(fmt.Errorf("not implemented: ListContentsByType - listContentsByType"))
}

// ListContentsByGenre is the resolver for the listContentsByGenre field.
func (r *queryResolver) ListContentsByGenre(ctx context.Context, genreID int32) ([]*model.Content, error) {
	panic(fmt.Errorf("not implemented: ListContentsByGenre - listContentsByGenre"))
}

// Content returns graph.ContentResolver implementation.
func (r *Resolver) Content() graph.ContentResolver { return &contentResolver{r} }

type contentResolver struct{ *Resolver }
