package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/generated"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// Reviews is the resolver for the reviews field.
func (r *episodeResolver) Reviews(ctx context.Context, obj *model.Episode) ([]*model.Review, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	reviews, err := r.ReviewService.ListReviewsByEpisode(ctx, obj.ID, profileID, userID)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return reviews, nil
}

// CreateEpisode is the resolver for the createEpisode field.
func (r *mutationResolver) CreateEpisode(ctx context.Context, input model.CreateEpisodeInput) (*model.Episode, error) {
	episode, err := r.EpisodeService.CreateEpisode(ctx, input)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return episode, nil
}

// UpdateEpisode is the resolver for the updateEpisode field.
func (r *mutationResolver) UpdateEpisode(ctx context.Context, id uuid.UUID, input model.UpdateEpisodeInput) (*model.Episode, error) {
	episode, err := r.EpisodeService.UpdateEpisode(ctx, id, input)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return episode, nil
}

// DeleteEpisode is the resolver for the deleteEpisode field.
func (r *mutationResolver) DeleteEpisode(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.EpisodeService.DeleteEpisode(ctx, id)
	if err != nil {
		return false, r.handleError(ctx, err)
	}

	return true, nil
}

// GetEpisode is the resolver for the getEpisode field.
func (r *queryResolver) GetEpisode(ctx context.Context, id uuid.UUID) (*model.Episode, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	episode, err := r.EpisodeService.GetEpisode(ctx, id, profileID, userID)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return episode, nil
}

// Episode returns generated.EpisodeResolver implementation.
func (r *Resolver) Episode() generated.EpisodeResolver { return &episodeResolver{r} }

type episodeResolver struct{ *Resolver }
