package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/generated"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/shared"
	historyv1 "github.com/ecbDeveloper/netflix-architecture/gen/go/history/v1"
	"github.com/google/uuid"
)

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.CreateProfileInput) (*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	profile, err := r.ProfileService.CreateProfile(ctx, input, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return profile, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id uuid.UUID, input model.UpdateProfileInput) (*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	profile, err := r.ProfileService.UpdateProfile(ctx, id, input, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return profile, nil
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, id uuid.UUID) (bool, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return false, r.handleError(err)
	}

	err = r.ProfileService.DeleteProfile(ctx, id, userID)
	if err != nil {
		return false, r.handleError(err)
	}

	r.Sessions.Remove(ctx, shared.SessionProfileIDKey)

	return true, nil
}

// SelectProfile is the resolver for the selectProfile field.
func (r *mutationResolver) SelectProfile(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return uuid.Nil, r.handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, id, userID)
	if err != nil {
		return uuid.Nil, r.handleError(err)
	}

	r.Sessions.Put(ctx, shared.SessionProfileIDKey, id)

	return profile.ID, nil
}

// Reviews is the resolver for the reviews field.
func (r *profileResolver) Reviews(ctx context.Context, obj *model.Profile) ([]*model.Review, error) {
	reviews, err := r.ReviewService.ListReviewsByProfile(ctx, obj.ID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return reviews, nil
}

// WatchHistories is the resolver for the watchHistories field.
func (r *profileResolver) WatchHistories(ctx context.Context, obj *model.Profile) ([]*model.WatchHistory, error) {
	resp, err := r.HistoryClient.ListWatchHistory(ctx, &historyv1.ListWatchHistoryRequest{
		ProfileId: obj.ID.String(),
	})
	if err != nil {
		return nil, r.handleGRPCError(err)
	}

	result := make([]*model.WatchHistory, len(resp.Histories))
	for i, h := range resp.Histories {
		result[i] = protoToWatchHistory(h)
	}

	return result, nil
}

// GetProfile is the resolver for the getProfile field.
func (r *queryResolver) GetProfile(ctx context.Context, id uuid.UUID) (*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, id, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return profile, nil
}

// ListProfiles is the resolver for the listProfiles field.
func (r *queryResolver) ListProfiles(ctx context.Context) ([]*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	profiles, err := r.ProfileService.ListProfilesByUser(ctx, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return profiles, nil
}

// Profile returns generated.ProfileResolver implementation.
func (r *Resolver) Profile() generated.ProfileResolver { return &profileResolver{r} }

type profileResolver struct{ *Resolver }
