package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/shared"
	historypb "github.com/ecbDeveloper/netflix-architecture/proto/history"
	"github.com/google/uuid"
)

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.CreateProfileInput) (*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to create profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	profile, err := r.ProfileService.CreateProfile(ctx, input, userID)
	if err != nil {
		r.Logger.Error("failed to create profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	return profile, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id uuid.UUID, input model.UpdateProfileInput) (*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to update profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	profile, err := r.ProfileService.UpdateProfile(ctx, id, input, userID)
	if err != nil {
		r.Logger.Error("failed to update profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	return profile, nil
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, id uuid.UUID) (bool, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to delete profile", slog.Any("error", err))
		return false, handleError(err)
	}

	err = r.ProfileService.DeleteProfile(ctx, id, userID)
	if err != nil {
		r.Logger.Error("failed to delete profile", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// SelectProfile is the resolver for the selectProfile field.
func (r *mutationResolver) SelectProfile(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to select profile", slog.Any("error", err))
		return uuid.Nil, handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, id, userID)
	if err != nil {
		r.Logger.Error("failed to select profile", slog.Any("error", err))
		return uuid.Nil, handleError(err)
	}

	r.Sessions.Put(ctx, shared.SessionProfileIDKey, id)

	return profile.ID, nil
}

// Reviews is the resolver for the reviews field.
func (r *profileResolver) Reviews(ctx context.Context, obj *model.Profile) ([]*model.Review, error) {
	reviews, err := r.ReviewService.ListReviewsByProfile(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("failed to list reviews", slog.Any("error", err))
		return nil, handleError(err)
	}

	return reviews, nil
}

// WatchHistories is the resolver for the watchHistories field.
func (r *profileResolver) WatchHistories(ctx context.Context, obj *model.Profile) ([]*model.WatchHistory, error) {
	resp, err := r.HistoryClient.ListWatchHistory(ctx, &historypb.ListWatchHistoryRequest{
		ProfileId: obj.ID.String(),
	})
	if err != nil {
		r.Logger.Error("failed to list watch histories via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	result := make([]*model.WatchHistory, len(resp.Histories))
	for i, h := range resp.Histories {
		result[i] = protoToWatchHistory(h)
	}

	return result, nil
}

// GetProfile is the resolver for the getProfile field.
func (r *queryResolver) GetProfile(ctx context.Context) (*model.Profile, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse profile id to get it", slog.Any("error", err))
		return nil, handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to get profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, profileID, userID)
	if err != nil {
		r.Logger.Error("failed to get profile", slog.Any("error", err))
		return nil, handleError(err)
	}

	return profile, nil
}

// ListProfiles is the resolver for the listProfiles field.
func (r *queryResolver) ListProfiles(ctx context.Context) ([]*model.Profile, error) {
	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to parse user id to list profiles", slog.Any("error", err))
		return nil, handleError(err)
	}

	profiles, err := r.ProfileService.ListProfilesByUser(ctx, userID)
	if err != nil {
		r.Logger.Error("failed to list profiles", slog.Any("error", err))
		return nil, handleError(err)
	}

	return profiles, nil
}

// Profile returns graph.ProfileResolver implementation.
func (r *Resolver) Profile() graph.ProfileResolver { return &profileResolver{r} }

type profileResolver struct{ *Resolver }
