package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to create review", slog.Any("error", err))
		return nil, handleError(err)
	}

	review, err := r.ReviewService.CreateReview(ctx, input, profileID)
	if err != nil {
		r.Logger.Error("failed to create review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id uuid.UUID, input model.UpdateReviewInput) (*model.Review, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to update review", slog.Any("error", err))
		return nil, handleError(err)
	}

	review, err := r.ReviewService.UpdateReview(ctx, id, input, profileID)
	if err != nil {
		r.Logger.Error("failed to update review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to delete review", slog.Any("error", err))
		return false, handleError(err)
	}

	err = r.ReviewService.DeleteReview(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to delete review", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetReview is the resolver for the getReview field.
func (r *queryResolver) GetReview(ctx context.Context, id uuid.UUID) (*model.Review, error) {
	review, err := r.ReviewService.GetReview(ctx, id)
	if err != nil {
		r.Logger.Error("failed to get review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// Profile is the resolver for the profile field.
func (r *reviewResolver) Profile(ctx context.Context, obj *model.Review) (*model.Profile, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id", slog.Any("error", err))
		return nil, handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user id", slog.Any("error", err))
		return nil, handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, profileID, userID)
	if err != nil {
		r.Logger.Error("failed to get profile %v: %w", profileID, err)
		return nil, handleError(err)
	}

	return profile, nil
}

// Review returns graph.ReviewResolver implementation.
func (r *Resolver) Review() graph.ReviewResolver { return &reviewResolver{r} }

type reviewResolver struct{ *Resolver }
