package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/apperror"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/generated"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	review, err := r.ReviewService.CreateReview(ctx, input, profileID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return review, nil
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id uuid.UUID, input model.UpdateReviewInput) (*model.Review, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	review, err := r.ReviewService.UpdateReview(ctx, id, input, profileID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return review, nil
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return false, r.handleError(err)
	}

	err = r.ReviewService.DeleteReview(ctx, id, profileID)
	if err != nil {
		return false, r.handleError(err)
	}

	return true, nil
}

// GetReview is the resolver for the getReview field.
func (r *queryResolver) GetReview(ctx context.Context, id uuid.UUID) (*model.Review, error) {
	review, err := r.ReviewService.GetReview(ctx, id)
	if err != nil {
		return nil, r.handleError(err)
	}

	return review, nil
}

// Profile is the resolver for the profile field.
func (r *reviewResolver) Profile(ctx context.Context, obj *model.Review) (*model.Profile, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	profile, err := r.ProfileService.GetProfile(ctx, profileID, userID)
	if err != nil {
		return nil, r.handleError(err)
	}

	return profile, nil
}

// Content is the resolver for the content field.
func (r *reviewResolver) Content(ctx context.Context, obj *model.Review) (model.ReviewedContent, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(err)
	}

	if obj.EpisodeID != uuid.Nil {
		episode, err := r.EpisodeService.GetEpisode(ctx, obj.EpisodeID, profileID, userID)
		if err != nil {
			return nil, r.handleError(err)
		}

		return episode, nil
	}

	if obj.MovieID != uuid.Nil {
		content, err := r.ContentService.GetContent(ctx, obj.MovieID, profileID, userID)
		if err != nil {
			return nil, r.handleError(err)
		}

		return content, nil
	}

	return nil, r.handleError(&apperror.UnprocessableEntityError{Message: "it was not possible to find the reviewed content"})
}

// Review returns generated.ReviewResolver implementation.
func (r *Resolver) Review() generated.ReviewResolver { return &reviewResolver{r} }

type reviewResolver struct{ *Resolver }
