package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/google/uuid"
)

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input model.CreateSeriesInput) (*model.Series, error) {
	s, err := r.SeriesService.CreateSeries(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// UpdateSeries is the resolver for the updateSeries field.
func (r *mutationResolver) UpdateSeries(ctx context.Context, id uuid.UUID, input model.UpdateSeriesInput) (*model.Series, error) {
	s, err := r.SeriesService.UpdateSeries(ctx, id, input)
	if err != nil {
		r.Logger.Error("failed to update series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// DeleteSeries is the resolver for the deleteSeries field.
func (r *mutationResolver) DeleteSeries(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.SeriesService.DeleteSeries(ctx, id)
	if err != nil {
		r.Logger.Error("failed to delete series", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetSeries is the resolver for the getSeries field.
func (r *queryResolver) GetSeries(ctx context.Context, id uuid.UUID) (*model.Series, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to get series", slog.Any("error", err))
		return nil, handleError(err)
	}

	s, err := r.SeriesService.GetSeries(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to get series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// ListSeries is the resolver for the listSeries field.
func (r *queryResolver) ListSeries(ctx context.Context) ([]*model.Series, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to list series", slog.Any("error", err))
		return nil, handleError(err)
	}

	series, err := r.SeriesService.ListSeries(ctx, profileID)
	if err != nil {
		r.Logger.Error("failed to list all series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return series, nil
}

// Episodes is the resolver for the episodes field.
func (r *seriesResolver) Episodes(ctx context.Context, obj *model.Series) ([]*model.Episode, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to get series", slog.Any("error", err))
		return nil, handleError(err)
	}

	episodes, err := r.EpisodeService.ListEpisodesBySeries(ctx, obj.ID, profileID)
	if err != nil {
		r.Logger.Error("failed to list episodes", slog.Any("error", err))
		return nil, handleError(err)
	}

	return episodes, nil
}

// Series returns graph.SeriesResolver implementation.
func (r *Resolver) Series() graph.SeriesResolver { return &seriesResolver{r} }

type seriesResolver struct{ *Resolver }
