package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/apperror"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/generated"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/shared"
	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.UserService.CreateUser(ctx, input)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input model.UpdateUserInput) (*model.User, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	if sessionUserID != id {
		return nil, r.handleError(ctx, &apperror.ForbiddenError{Message: "you can't update others users"})
	}

	user, err := r.UserService.UpdateUser(ctx, id, input)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return false, r.handleError(ctx, err)
	}

	if sessionUserID != id {
		return false, r.handleError(ctx, &apperror.ForbiddenError{Message: "you can't delete others users"})
	}

	err = r.UserService.DeleteUser(ctx, id)
	if err != nil {
		return false, r.handleError(ctx, err)
	}

	if err := r.Sessions.Destroy(ctx); err != nil {
		return false, r.handleError(ctx, err)
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id uuid.UUID) (*model.User, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	sessionRoleID, err := r.getUserRoleIDFromSession(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	if sessionUserID != id && sessionRoleID != shared.DBRoleAdmin {
		return nil, r.handleError(ctx, &apperror.ForbiddenError{Message: "you can't access others users data"})
	}

	user, err := r.UserService.GetUser(ctx, id)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return user, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.ListUsers(ctx)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return users, nil
}

// Profiles is the resolver for the profiles field.
func (r *userResolver) Profiles(ctx context.Context, obj *model.User) ([]*model.Profile, error) {
	profiles, err := r.ProfileService.ListProfilesByUser(ctx, obj.ID)
	if err != nil {
		return nil, r.handleError(ctx, err)
	}

	return profiles, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
