package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/apperror"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/apps/api/internal/graph/model"
	historypb "github.com/ecbDeveloper/netflix-architecture/proto/history"
	recommendationpb "github.com/ecbDeveloper/netflix-architecture/proto/recommendation"
	"github.com/google/uuid"
)

// RecordWatchHistory is the resolver for the recordWatchHistory field.
func (r *mutationResolver) RecordWatchHistory(ctx context.Context, input model.CreateWatchHistoryInput) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to create watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	reqBody := &historypb.RecordWatchHistoryRequest{
		ProfileId: profileID.String(),
		GenreId:   *input.GenreID,
	}

	if input.MovieID != nil {
		movieStr := input.MovieID.String()
		reqBody.MovieId = &movieStr
	}

	if input.EpisodeID != nil {
		episodeStr := input.EpisodeID.String()
		reqBody.EpisodeId = &episodeStr
	}

	if input.LastPositionSeconds != nil {
		reqBody.LastPositionSeconds = input.LastPositionSeconds
	}

	if input.IsCompleted != nil {
		reqBody.IsCompleted = input.IsCompleted
	}

	resp, err := r.HistoryClient.RecordWatchHistory(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to record watch history via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	return protoToWatchHistory(resp), nil
}

// UpdateWatchHistory is the resolver for the updateWatchHistory field.
func (r *mutationResolver) UpdateWatchHistory(ctx context.Context, id uuid.UUID, input model.UpdateWatchHistoryInput) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to update watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	reqBody := &historypb.UpdateWatchProgressRequest{
		Id:        id.String(),
		ProfileId: profileID.String(),
	}

	if input.LastPositionSeconds != nil {
		reqBody.LastPositionSeconds = input.LastPositionSeconds
	}
	if input.IsCompleted != nil {
		reqBody.IsCompleted = input.IsCompleted
	}

	resp, err := r.HistoryClient.UpdateWatchProgress(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to update watch history via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	return protoToWatchHistory(resp), nil
}

// DeleteWatchHistory is the resolver for the deleteWatchHistory field.
func (r *mutationResolver) DeleteWatchHistory(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to delete watch history", slog.Any("error", err))
		return false, handleError(err)
	}

	reqBody := &historypb.DeleteWatchHistoryRequest{
		Id:        id.String(),
		ProfileId: profileID.String(),
	}

	_, err = r.HistoryClient.DeleteWatchHistory(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to delete watch history via grpc", slog.Any("error", err))
		return false, handleGRPCError(err)
	}

	return true, nil
}

// GetWatchHistory is the resolver for the getWatchHistory field.
func (r *queryResolver) GetWatchHistory(ctx context.Context, id uuid.UUID) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to get one watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	reqBody := &historypb.GetWatchHistoryRequest{
		Id:        id.String(),
		ProfileId: profileID.String(),
	}

	resp, err := r.HistoryClient.GetWatchHistory(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to get watch history via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	return protoToWatchHistory(resp), nil
}

// MostWatchedContents is the resolver for the mostWatchedContents field.
func (r *queryResolver) MostWatchedContents(ctx context.Context, input *model.PaginationInput) ([]*model.MostWatchedContent, error) {
	var limit int32 = 10
	if input.Limit != nil {
		limit = *input.Limit
	}

	var offset int32 = 0
	if input.Offset != nil {
		offset = *input.Offset
	}

	reqBody := &historypb.GetMostWatchedRequest{
		Limit:  limit,
		Offset: offset,
	}

	resp, err := r.HistoryClient.GetMostWatched(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to get most watched via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	result := make([]*model.MostWatchedContent, len(resp.Items))
	for i, item := range resp.Items {
		contentID, _ := uuid.Parse(item.ContentId)
		result[i] = &model.MostWatchedContent{
			ContentID:   contentID,
			ContentType: hContentTypeToGraph[item.ContentType],
			GenreID:     item.GenreId,
			WatchCount:  int32(item.WatchCount),
		}
	}
	return result, nil
}

// RecentlyWatchedContents is the resolver for the recentlyWatchedContents field.
func (r *queryResolver) RecentlyWatchedContents(ctx context.Context, input *model.PaginationInput) ([]*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id for recently watched", slog.Any("error", err))
		return nil, handleError(err)
	}

	var limit int32 = 10
	if input.Limit != nil {
		limit = *input.Limit
	}

	var offset int32 = 0
	if input.Offset != nil {
		offset = *input.Offset
	}

	reqBody := &historypb.GetRecentlyWatchedRequest{
		ProfileId: profileID.String(),
		Limit:     limit,
		Offset:    offset,
	}

	resp, err := r.HistoryClient.GetRecentlyWatched(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to get recently watched via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	result := make([]*model.WatchHistory, len(resp.Histories))
	for i, h := range resp.Histories {
		result[i] = protoToWatchHistory(h)
	}
	return result, nil
}

// GetRecommendations is the resolver for the getRecommendations field.
func (r *queryResolver) GetRecommendations(ctx context.Context, limit *int32) ([]*model.RecommendedContent, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id for recommendations", slog.Any("error", err))
		return nil, handleError(err)
	}

	var l int32 = 20
	if limit != nil {
		l = *limit
	}

	reqBody := &recommendationpb.GetRecommendationsRequest{
		ProfileId: profileID.String(),
		Limit:     l,
	}

	resp, err := r.RecommendationClient.GetRecommendations(ctx, reqBody)
	if err != nil {
		r.Logger.Error("failed to get recommendations via grpc", slog.Any("error", err))
		return nil, handleGRPCError(err)
	}

	result := make([]*model.RecommendedContent, len(resp.Recommendations))
	for i, rec := range resp.Recommendations {
		contentID, _ := uuid.Parse(rec.ContentId)
		result[i] = &model.RecommendedContent{
			ContentID:   contentID,
			ContentType: recContentTypeToGraph[rec.ContentType],
			Score:       rec.Score,
			Reason:      rec.Reason,
		}
	}
	return result, nil
}

// Content is the resolver for the content field.
func (r *watchHistoryResolver) Content(ctx context.Context, obj *model.WatchHistory) (model.WatchedContent, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id", slog.Any("error", err))
		return nil, handleError(err)
	}

	userID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user id", slog.Any("error", err))
		return nil, handleError(err)
	}

	if obj.EpisodeID != uuid.Nil {
		episode, err := r.EpisodeService.GetEpisode(ctx, obj.EpisodeID, profileID, userID)
		if err != nil {
			r.Logger.Error("failed to get episode", slog.Any("error", err))
			return nil, handleError(err)
		}

		return episode, nil
	}

	if obj.MovieID != uuid.Nil {
		content, err := r.ContentService.GetContent(ctx, obj.MovieID, profileID, userID)
		if err != nil {
			r.Logger.Error("failed to get content", slog.Any("error", err))
			return nil, handleError(err)
		}

		return content, nil
	}

	return nil, handleError(&apperror.UnprocessableEntityError{Message: "it was not possible to find the watched content"})
}

// WatchHistory returns graph.WatchHistoryResolver implementation.
func (r *Resolver) WatchHistory() graph.WatchHistoryResolver { return &watchHistoryResolver{r} }

type watchHistoryResolver struct{ *Resolver }
