// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recommendation/recommendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProfileId        string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TopRatedContents []*TopRatedContent     `protobuf:"bytes,3,rep,name=top_rated_contents,json=topRatedContents,proto3" json:"top_rated_contents,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRecommendationsRequest) GetTopRatedContents() []*TopRatedContent {
	if x != nil {
		return x.TopRatedContents
	}
	return nil
}

type TopRatedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "movie" or "episode"
	GenreId       int32                  `protobuf:"varint,3,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	AvgRating     float64                `protobuf:"fixed64,4,opt,name=avg_rating,json=avgRating,proto3" json:"avg_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRatedContent) Reset() {
	*x = TopRatedContent{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRatedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRatedContent) ProtoMessage() {}

func (x *TopRatedContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRatedContent.ProtoReflect.Descriptor instead.
func (*TopRatedContent) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *TopRatedContent) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *TopRatedContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TopRatedContent) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *TopRatedContent) GetAvgRating() float64 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

type RecommendedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "movie" or "episode"
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // "same_genre", "most_watched", "top_rated"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedContent) Reset() {
	*x = RecommendedContent{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedContent) ProtoMessage() {}

func (x *RecommendedContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedContent.ProtoReflect.Descriptor instead.
func (*RecommendedContent) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendedContent) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *RecommendedContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RecommendedContent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendedContent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendedContent  `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*RecommendedContent {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_proto_recommendation_recommendation_proto protoreflect.FileDescriptor

const file_proto_recommendation_recommendation_proto_rawDesc = "" +
	"\n" +
	")proto/recommendation/recommendation.proto\x12\x0erecommendation\"\x9f\x01\n" +
	"\x19GetRecommendationsRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12M\n" +
	"\x12top_rated_contents\x18\x03 \x03(\v2\x1f.recommendation.TopRatedContentR\x10topRatedContents\"\x8d\x01\n" +
	"\x0fTopRatedContent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x19\n" +
	"\bgenre_id\x18\x03 \x01(\x05R\agenreId\x12\x1d\n" +
	"\n" +
	"avg_rating\x18\x04 \x01(\x01R\tavgRating\"\x84\x01\n" +
	"\x12RecommendedContent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"j\n" +
	"\x1aGetRecommendationsResponse\x12L\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\".recommendation.RecommendedContentR\x0frecommendations2\x84\x01\n" +
	"\x15RecommendationService\x12k\n" +
	"\x12GetRecommendations\x12).recommendation.GetRecommendationsRequest\x1a*.recommendation.GetRecommendationsResponseBCZAgithub.com/ecbDeveloper/netflix-architecture/proto/recommendationb\x06proto3"

var (
	file_proto_recommendation_recommendation_proto_rawDescOnce sync.Once
	file_proto_recommendation_recommendation_proto_rawDescData []byte
)

func file_proto_recommendation_recommendation_proto_rawDescGZIP() []byte {
	file_proto_recommendation_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_recommendation_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)))
	})
	return file_proto_recommendation_recommendation_proto_rawDescData
}

var file_proto_recommendation_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_recommendation_recommendation_proto_goTypes = []any{
	(*GetRecommendationsRequest)(nil),  // 0: recommendation.GetRecommendationsRequest
	(*TopRatedContent)(nil),            // 1: recommendation.TopRatedContent
	(*RecommendedContent)(nil),         // 2: recommendation.RecommendedContent
	(*GetRecommendationsResponse)(nil), // 3: recommendation.GetRecommendationsResponse
}
var file_proto_recommendation_recommendation_proto_depIdxs = []int32{
	1, // 0: recommendation.GetRecommendationsRequest.top_rated_contents:type_name -> recommendation.TopRatedContent
	2, // 1: recommendation.GetRecommendationsResponse.recommendations:type_name -> recommendation.RecommendedContent
	0, // 2: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.GetRecommendationsRequest
	3, // 3: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.GetRecommendationsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_recommendation_recommendation_proto_init() }
func file_proto_recommendation_recommendation_proto_init() {
	if File_proto_recommendation_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommendation_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_recommendation_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_recommendation_recommendation_proto_msgTypes,
	}.Build()
	File_proto_recommendation_recommendation_proto = out.File
	file_proto_recommendation_recommendation_proto_goTypes = nil
	file_proto_recommendation_recommendation_proto_depIdxs = nil
}
