// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentTypeEnum string

const (
	ContentTypeEnumMOVIE  ContentTypeEnum = "MOVIE"
	ContentTypeEnumSERIES ContentTypeEnum = "SERIES"
)

func (e *ContentTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentTypeEnum(s)
	case string:
		*e = ContentTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentTypeEnum: %T", src)
	}
	return nil
}

type NullContentTypeEnum struct {
	ContentTypeEnum ContentTypeEnum `json:"content_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if ContentTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ContentTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentTypeEnum), nil
}

type Recommendation struct {
	ID          uuid.UUID        `json:"id"`
	ProfileID   uuid.UUID        `json:"profile_id"`
	ContentID   uuid.UUID        `json:"content_id"`
	ContentType ContentTypeEnum  `json:"content_type"`
	Score       float64          `json:"score"`
	Reason      string           `json:"reason"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
