// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

type ContentGenre struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type CreateEpisodeInput struct {
	SeriesID        uuid.UUID      `json:"seriesId"`
	Season          int32          `json:"season"`
	EpisodeNumber   int32          `json:"episodeNumber"`
	Title           string         `json:"title"`
	DurationMinutes int32          `json:"durationMinutes"`
	EpisodeFile     graphql.Upload `json:"episodeFile"`
}

type CreateMovieInput struct {
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	DurationMinutes int32          `json:"durationMinutes"`
	ReleaseDate     string         `json:"releaseDate"`
	MaturityRating  MaturityRating `json:"maturityRating"`
	MovieFile       graphql.Upload `json:"movieFile"`
	GenreID         int32          `json:"genreId"`
}

type CreateProfileInput struct {
	Name                string `json:"name"`
	HasParentalControls *bool  `json:"hasParentalControls,omitempty"`
}

type CreateReviewInput struct {
	MovieID   *uuid.UUID `json:"movieId,omitempty"`
	EpisodeID *uuid.UUID `json:"episodeId,omitempty"`
	Rating    int32      `json:"rating"`
	Comment   *string    `json:"comment,omitempty"`
}

type CreateSeriesInput struct {
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	ReleaseDate    string         `json:"releaseDate"`
	MaturityRating MaturityRating `json:"maturityRating"`
	GenreID        int32          `json:"genreId"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Cpf      string `json:"cpf"`
	Password string `json:"password"`
}

type CreateWatchHistoryInput struct {
	MovieID             *uuid.UUID `json:"movieId,omitempty"`
	EpisodeID           *uuid.UUID `json:"episodeId,omitempty"`
	LastPositionSeconds *int32     `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool      `json:"isCompleted,omitempty"`
}

type Episode struct {
	ID              uuid.UUID `json:"id"`
	SeriesID        uuid.UUID `json:"seriesId"`
	Season          int32     `json:"season"`
	EpisodeNumber   int32     `json:"episodeNumber"`
	Title           string    `json:"title"`
	DurationMinutes int32     `json:"durationMinutes"`
	ContentURL      string    `json:"contentURL"`
	CreatedAt       string    `json:"createdAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Movie struct {
	ID              uuid.UUID      `json:"id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	DurationMinutes int32          `json:"durationMinutes"`
	ReleaseDate     string         `json:"releaseDate"`
	MaturityRating  MaturityRating `json:"maturityRating"`
	ContentURL      string         `json:"contentUrl"`
	GenreID         int32          `json:"genreId"`
}

type Mutation struct {
}

type Profile struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"userId"`
	Name                string    `json:"name"`
	HasParentalControls bool      `json:"hasParentalControls"`
	CreatedAt           string    `json:"createdAt"`
	UpdatedAt           string    `json:"updatedAt"`
}

type Query struct {
}

type Review struct {
	ID        uuid.UUID  `json:"id"`
	ProfileID uuid.UUID  `json:"profileId"`
	MovieID   *uuid.UUID `json:"movieId,omitempty"`
	EpisodeID *uuid.UUID `json:"episodeId,omitempty"`
	Rating    int32      `json:"rating"`
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}

type Series struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	ReleaseDate    string         `json:"releaseDate"`
	MaturityRating MaturityRating `json:"maturityRating"`
	GenreID        int32          `json:"genreId"`
}

type UpdateEpisodeInput struct {
	Season          *int32  `json:"season,omitempty"`
	EpisodeNumber   *int32  `json:"episodeNumber,omitempty"`
	Title           *string `json:"title,omitempty"`
	DurationMinutes *int32  `json:"durationMinutes,omitempty"`
}

type UpdateMovieInput struct {
	Title           *string         `json:"title,omitempty"`
	Description     *string         `json:"description,omitempty"`
	DurationMinutes *int32          `json:"durationMinutes,omitempty"`
	ReleaseDate     *string         `json:"releaseDate,omitempty"`
	MaturityRating  *MaturityRating `json:"maturityRating,omitempty"`
	GenreID         *int32          `json:"genreId,omitempty"`
}

type UpdateProfileInput struct {
	Name                *string `json:"name,omitempty"`
	HasParentalControls *bool   `json:"hasParentalControls,omitempty"`
}

type UpdateReviewInput struct {
	ID      uuid.UUID `json:"id"`
	Rating  *int32    `json:"rating,omitempty"`
	Comment *string   `json:"comment,omitempty"`
}

type UpdateSeriesInput struct {
	Title          *string         `json:"title,omitempty"`
	Description    *string         `json:"description,omitempty"`
	ReleaseDate    *string         `json:"releaseDate,omitempty"`
	MaturityRating *MaturityRating `json:"maturityRating,omitempty"`
	GenreID        *int32          `json:"genreId,omitempty"`
}

type UpdateUserInput struct {
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdateWatchHistoryInput struct {
	ID                  uuid.UUID `json:"id"`
	LastPositionSeconds *int32    `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool     `json:"isCompleted,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Cpf       string    `json:"cpf"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
	RoleID    int32     `json:"roleId"`
}

type WatchHistory struct {
	ID                  uuid.UUID  `json:"id"`
	ProfileID           uuid.UUID  `json:"profileId"`
	MovieID             *uuid.UUID `json:"movieId,omitempty"`
	EpisodeID           *uuid.UUID `json:"episodeId,omitempty"`
	WatchedAt           string     `json:"watchedAt"`
	LastPositionSeconds *int32     `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool      `json:"isCompleted,omitempty"`
}

type MaturityRating string

const (
	MaturityRatingL        MaturityRating = "L"
	MaturityRatingRating10 MaturityRating = "RATING_10"
	MaturityRatingRating12 MaturityRating = "RATING_12"
	MaturityRatingRating14 MaturityRating = "RATING_14"
	MaturityRatingRating16 MaturityRating = "RATING_16"
	MaturityRatingRating18 MaturityRating = "RATING_18"
)

var AllMaturityRating = []MaturityRating{
	MaturityRatingL,
	MaturityRatingRating10,
	MaturityRatingRating12,
	MaturityRatingRating14,
	MaturityRatingRating16,
	MaturityRatingRating18,
}

func (e MaturityRating) IsValid() bool {
	switch e {
	case MaturityRatingL, MaturityRatingRating10, MaturityRatingRating12, MaturityRatingRating14, MaturityRatingRating16, MaturityRatingRating18:
		return true
	}
	return false
}

func (e MaturityRating) String() string {
	return string(e)
}

func (e *MaturityRating) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MaturityRating(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MaturityRating", str)
	}
	return nil
}

func (e MaturityRating) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MaturityRating) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MaturityRating) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "ADMIN"
	UserRoleMember UserRole = "MEMBER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleMember,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleMember:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
