// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateEpisodeInput struct {
	SeriesID        int32  `json:"seriesId"`
	Season          int32  `json:"season"`
	EpisodeNumber   int32  `json:"episodeNumber"`
	Title           string `json:"title"`
	DurationMinutes int32  `json:"durationMinutes"`
}

type CreateMovieInput struct {
	Title           string `json:"title"`
	Description     string `json:"description"`
	DurationMinutes int32  `json:"durationMinutes"`
	ReleaseDate     string `json:"releaseDate"`
	MaturityRating  string `json:"maturityRating"`
	ContentURL      string `json:"contentUrl"`
}

type CreateProfileInput struct {
	UserID              string `json:"userId"`
	Name                string `json:"name"`
	HasParentalControls *bool  `json:"hasParentalControls,omitempty"`
}

type CreateReviewInput struct {
	ProfileID string  `json:"profileId"`
	MovieID   *string `json:"movieId,omitempty"`
	EpisodeID *string `json:"episodeId,omitempty"`
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
}

type CreateSeriesInput struct {
	Title          string  `json:"title"`
	Description    *string `json:"description,omitempty"`
	ReleaseDate    *string `json:"releaseDate,omitempty"`
	MaturityRating *string `json:"maturityRating,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Cpf      string `json:"cpf"`
	Password string `json:"password"`
}

type CreateWatchHistoryInput struct {
	ProfileID           string  `json:"profileId"`
	MovieID             *string `json:"movieId,omitempty"`
	EpisodeID           *string `json:"episodeId,omitempty"`
	LastPositionSeconds *int32  `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool   `json:"isCompleted,omitempty"`
}

type Episode struct {
	ID              string    `json:"id"`
	SeriesID        int32     `json:"seriesId"`
	Season          int32     `json:"season"`
	EpisodeNumber   int32     `json:"episodeNumber"`
	Title           string    `json:"title"`
	DurationMinutes int32     `json:"durationMinutes"`
	CreatedAt       string    `json:"createdAt"`
	Reviews         []*Review `json:"reviews"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Movie struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	DurationMinutes int32     `json:"durationMinutes"`
	ReleaseDate     string    `json:"releaseDate"`
	MaturityRating  string    `json:"maturityRating"`
	ContentURL      string    `json:"contentUrl"`
	Reviews         []*Review `json:"reviews"`
}

type Mutation struct {
}

type Profile struct {
	ID                  string          `json:"id"`
	UserID              string          `json:"userId"`
	Name                string          `json:"name"`
	HasParentalControls bool            `json:"hasParentalControls"`
	CreatedAt           string          `json:"createdAt"`
	UpdatedAt           string          `json:"updatedAt"`
	Reviews             []*Review       `json:"reviews"`
	WatchHistories      []*WatchHistory `json:"watchHistories"`
}

type Query struct {
}

type Review struct {
	ID        string  `json:"id"`
	ProfileID string  `json:"profileId"`
	MovieID   *string `json:"movieId,omitempty"`
	EpisodeID *string `json:"episodeId,omitempty"`
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type Series struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Description    *string    `json:"description,omitempty"`
	ReleaseDate    *string    `json:"releaseDate,omitempty"`
	MaturityRating *string    `json:"maturityRating,omitempty"`
	Episodes       []*Episode `json:"episodes"`
}

type UpdateEpisodeInput struct {
	Season          *int32  `json:"season,omitempty"`
	EpisodeNumber   *int32  `json:"episodeNumber,omitempty"`
	Title           *string `json:"title,omitempty"`
	DurationMinutes *int32  `json:"durationMinutes,omitempty"`
}

type UpdateMovieInput struct {
	Title           *string `json:"title,omitempty"`
	Description     *string `json:"description,omitempty"`
	DurationMinutes *int32  `json:"durationMinutes,omitempty"`
	ReleaseDate     *string `json:"releaseDate,omitempty"`
	MaturityRating  *string `json:"maturityRating,omitempty"`
	ContentURL      *string `json:"contentUrl,omitempty"`
}

type UpdateProfileInput struct {
	Name                *string `json:"name,omitempty"`
	HasParentalControls *bool   `json:"hasParentalControls,omitempty"`
}

type UpdateReviewInput struct {
	Rating  *int32  `json:"rating,omitempty"`
	Comment *string `json:"comment,omitempty"`
}

type UpdateSeriesInput struct {
	Title          *string `json:"title,omitempty"`
	Description    *string `json:"description,omitempty"`
	ReleaseDate    *string `json:"releaseDate,omitempty"`
	MaturityRating *string `json:"maturityRating,omitempty"`
}

type UpdateUserInput struct {
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UpdateWatchHistoryInput struct {
	LastPositionSeconds *int32 `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool  `json:"isCompleted,omitempty"`
}

type User struct {
	ID        string     `json:"id"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	Cpf       string     `json:"cpf"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	Profiles  []*Profile `json:"profiles"`
}

type WatchHistory struct {
	ID                  string  `json:"id"`
	ProfileID           string  `json:"profileId"`
	MovieID             *string `json:"movieId,omitempty"`
	EpisodeID           *string `json:"episodeId,omitempty"`
	WatchedAt           string  `json:"watchedAt"`
	LastPositionSeconds *int32  `json:"lastPositionSeconds,omitempty"`
	IsCompleted         *bool   `json:"isCompleted,omitempty"`
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "ADMIN"
	UserRoleMember UserRole = "MEMBER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleMember,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleMember:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
