// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WatchHistory struct {
	ID                  uuid.UUID        `json:"id"`
	ProfileID           uuid.UUID        `json:"profile_id"`
	MovieID             pgtype.UUID      `json:"movie_id"`
	EpisodeID           pgtype.UUID      `json:"episode_id"`
	GenreID             pgtype.Int4      `json:"genre_id"`
	WatchedAt           pgtype.Timestamp `json:"watched_at"`
	LastPositionSeconds pgtype.Int4      `json:"last_position_seconds"`
	IsCompleted         pgtype.Bool      `json:"is_completed"`
}
