// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_genres.sql

package sqlc

import (
	"context"
)

const listContentGenres = `-- name: ListContentGenres :many
SELECT id, description FROM content_genres
`

func (q *Queries) ListContentGenres(ctx context.Context) ([]ContentGenre, error) {
	rows, err := q.db.Query(ctx, listContentGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentGenre
	for rows.Next() {
		var i ContentGenre
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
