// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createContent = `-- name: CreateContent :exec
INSERT INTO contents (
  id, 
  title, 
  content_type, 
  description, 
  release_date, 
  maturity_rating
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id
`

type CreateContentParams struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	ContentType    ContentType    `json:"content_type"`
	Description    string         `json:"description"`
	ReleaseDate    time.Time      `json:"release_date"`
	MaturityRating MaturityRating `json:"maturity_rating"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) error {
	_, err := q.db.Exec(ctx, createContent,
		arg.ID,
		arg.Title,
		arg.ContentType,
		arg.Description,
		arg.ReleaseDate,
		arg.MaturityRating,
	)
	return err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM contents
WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContent, id)
	return err
}

const getContent = `-- name: GetContent :one
SELECT id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id
FROM contents
WHERE id = $1
`

func (q *Queries) GetContent(ctx context.Context, id uuid.UUID) (Content, error) {
	row := q.db.QueryRow(ctx, getContent, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentType,
		&i.Description,
		&i.ReleaseDate,
		&i.MaturityRating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GenreID,
	)
	return i, err
}

const listContents = `-- name: ListContents :many
SELECT id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id FROM contents
`

func (q *Queries) ListContents(ctx context.Context) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentType,
			&i.Description,
			&i.ReleaseDate,
			&i.MaturityRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GenreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsByGenre = `-- name: ListContentsByGenre :many
SELECT id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id FROM contents
WHERE genre_id = $1
`

func (q *Queries) ListContentsByGenre(ctx context.Context, genreID int32) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsByGenre, genreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentType,
			&i.Description,
			&i.ReleaseDate,
			&i.MaturityRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GenreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsByType = `-- name: ListContentsByType :many
SELECT id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id FROM contents
WHERE content_type = $1
`

func (q *Queries) ListContentsByType(ctx context.Context, contentType ContentType) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsByType, contentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentType,
			&i.Description,
			&i.ReleaseDate,
			&i.MaturityRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GenreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKidsContents = `-- name: ListKidsContents :many
SELECT id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id FROM contents
WHERE maturity_rating = 'L'
`

func (q *Queries) ListKidsContents(ctx context.Context) ([]Content, error) {
	rows, err := q.db.Query(ctx, listKidsContents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentType,
			&i.Description,
			&i.ReleaseDate,
			&i.MaturityRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GenreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE contents SET
  title = $2, 
	genre_id = $3,
  description = $4, 
  release_date = $5, 
  maturity_rating = $6
WHERE id = $1
RETURNING id, title, content_type, description, release_date, maturity_rating, created_at, updated_at, genre_id
`

type UpdateContentParams struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	GenreID        int32          `json:"genre_id"`
	Description    string         `json:"description"`
	ReleaseDate    time.Time      `json:"release_date"`
	MaturityRating MaturityRating `json:"maturity_rating"`
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, updateContent,
		arg.ID,
		arg.Title,
		arg.GenreID,
		arg.Description,
		arg.ReleaseDate,
		arg.MaturityRating,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentType,
		&i.Description,
		&i.ReleaseDate,
		&i.MaturityRating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GenreID,
	)
	return i, err
}
