// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (id, series_id, season, episode_number, title)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, series_id, season, episode_number, title, duration_seconds, content_url, created_at, updated_at, status
`

type CreateEpisodeParams struct {
	ID            uuid.UUID `json:"id"`
	SeriesID      uuid.UUID `json:"series_id"`
	Season        int32     `json:"season"`
	EpisodeNumber int32     `json:"episode_number"`
	Title         string    `json:"title"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.ID,
		arg.SeriesID,
		arg.Season,
		arg.EpisodeNumber,
		arg.Title,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationSeconds,
		&i.ContentUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisode, id)
	return err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, series_id, season, episode_number, title, duration_seconds, content_url, created_at, updated_at, status FROM episodes WHERE id = $1
`

func (q *Queries) GetEpisode(ctx context.Context, id uuid.UUID) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationSeconds,
		&i.ContentUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listEpisodesBySeries = `-- name: ListEpisodesBySeries :many
SELECT id, series_id, season, episode_number, title, duration_seconds, content_url, created_at, updated_at, status FROM episodes WHERE series_id = $1 ORDER BY season, episode_number
`

func (q *Queries) ListEpisodesBySeries(ctx context.Context, seriesID uuid.UUID) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Season,
			&i.EpisodeNumber,
			&i.Title,
			&i.DurationSeconds,
			&i.ContentUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes
SET season = $2, episode_number = $3, title = $4, duration_seconds = $5, content_url = $6, status = $7
WHERE id = $1
RETURNING id, series_id, season, episode_number, title, duration_seconds, content_url, created_at, updated_at, status
`

type UpdateEpisodeParams struct {
	ID              uuid.UUID     `json:"id"`
	Season          int32         `json:"season"`
	EpisodeNumber   int32         `json:"episode_number"`
	Title           string        `json:"title"`
	DurationSeconds pgtype.Int4   `json:"duration_seconds"`
	ContentUrl      pgtype.Text   `json:"content_url"`
	Status          ContentStatus `json:"status"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisode,
		arg.ID,
		arg.Season,
		arg.EpisodeNumber,
		arg.Title,
		arg.DurationSeconds,
		arg.ContentUrl,
		arg.Status,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationSeconds,
		&i.ContentUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
