// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType string

const (
	ContentTypeMOVIE  ContentType = "MOVIE"
	ContentTypeSERIES ContentType = "SERIES"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type MaturityRating string

const (
	MaturityRatingL  MaturityRating = "L"
	MaturityRating10 MaturityRating = "10"
	MaturityRating12 MaturityRating = "12"
	MaturityRating14 MaturityRating = "14"
	MaturityRating16 MaturityRating = "16"
	MaturityRating18 MaturityRating = "18"
)

func (e *MaturityRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaturityRating(s)
	case string:
		*e = MaturityRating(s)
	default:
		return fmt.Errorf("unsupported scan type for MaturityRating: %T", src)
	}
	return nil
}

type NullMaturityRating struct {
	MaturityRating MaturityRating `json:"maturity_rating"`
	Valid          bool           `json:"valid"` // Valid is true if MaturityRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaturityRating) Scan(value interface{}) error {
	if value == nil {
		ns.MaturityRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaturityRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaturityRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaturityRating), nil
}

type Content struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	ContentType    ContentType    `json:"content_type"`
	Description    string         `json:"description"`
	ReleaseDate    time.Time      `json:"release_date"`
	MaturityRating MaturityRating `json:"maturity_rating"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	GenreID        int32          `json:"genre_id"`
}

type ContentGenre struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
}

type Episode struct {
	ID              uuid.UUID `json:"id"`
	SeriesID        uuid.UUID `json:"series_id"`
	Season          int32     `json:"season"`
	EpisodeNumber   int32     `json:"episode_number"`
	Title           string    `json:"title"`
	DurationMinutes int32     `json:"duration_minutes"`
	ContentUrl      string    `json:"content_url"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Movie struct {
	ContentID       uuid.UUID `json:"content_id"`
	DurationMinutes int32     `json:"duration_minutes"`
	ContentUrl      string    `json:"content_url"`
}

type Profile struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	Name                string    `json:"name"`
	HasParentalControls bool      `json:"has_parental_controls"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Review struct {
	ID        uuid.UUID        `json:"id"`
	ProfileID uuid.UUID        `json:"profile_id"`
	MovieID   pgtype.UUID      `json:"movie_id"`
	EpisodeID pgtype.UUID      `json:"episode_id"`
	Rating    int32            `json:"rating"`
	Comment   pgtype.Text      `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Series struct {
	ContentID uuid.UUID `json:"content_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Cpf       string    `json:"cpf"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	RoleID    int32     `json:"role_id"`
}

type UsersRole struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}
