// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
  content_id, 
  duration_minutes, 
  content_url
) VALUES ($1, $2, $3)
RETURNING content_id, duration_minutes, content_url
`

type CreateMovieParams struct {
	ContentID       uuid.UUID `json:"content_id"`
	DurationMinutes int32     `json:"duration_minutes"`
	ContentUrl      string    `json:"content_url"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie, arg.ContentID, arg.DurationMinutes, arg.ContentUrl)
	var i Movie
	err := row.Scan(&i.ContentID, &i.DurationMinutes, &i.ContentUrl)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT
  c.id, c.title, c.description, m.duration_minutes, c.release_date,
  m.content_url, c.created_at, c.updated_at, c.maturity_rating, c.genre_id
FROM contents c
JOIN movies m ON m.content_id = c.id
WHERE c.id = $1
`

type GetMovieRow struct {
	ID              uuid.UUID      `json:"id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	DurationMinutes int32          `json:"duration_minutes"`
	ReleaseDate     pgtype.Date    `json:"release_date"`
	ContentUrl      string         `json:"content_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	MaturityRating  MaturityRating `json:"maturity_rating"`
	GenreID         int32          `json:"genre_id"`
}

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (GetMovieRow, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i GetMovieRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.ReleaseDate,
		&i.ContentUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaturityRating,
		&i.GenreID,
	)
	return i, err
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET duration_minutes = $2, content_url = $3
WHERE content_id = $1
RETURNING content_id, duration_minutes, content_url
`

type UpdateMovieParams struct {
	ContentID       uuid.UUID `json:"content_id"`
	DurationMinutes int32     `json:"duration_minutes"`
	ContentUrl      string    `json:"content_url"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie, arg.ContentID, arg.DurationMinutes, arg.ContentUrl)
	var i Movie
	err := row.Scan(&i.ContentID, &i.DurationMinutes, &i.ContentUrl)
	return i, err
}
