// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (content_id)
VALUES ($1)
RETURNING content_id
`

func (q *Queries) CreateSeries(ctx context.Context, contentID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSeries, contentID)
	var content_id uuid.UUID
	err := row.Scan(&content_id)
	return content_id, err
}

const getSeries = `-- name: GetSeries :one
SELECT
  c.id, c.title, c.description, c.release_date, c.created_at, c.updated_at, c.maturity_rating, c.genre_id
FROM contents c
JOIN series s ON s.content_id = c.id
WHERE c.id = $1
`

type GetSeriesRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	ReleaseDate    time.Time      `json:"release_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	MaturityRating MaturityRating `json:"maturity_rating"`
	GenreID        int32          `json:"genre_id"`
}

func (q *Queries) GetSeries(ctx context.Context, id uuid.UUID) (GetSeriesRow, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i GetSeriesRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaturityRating,
		&i.GenreID,
	)
	return i, err
}
