// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (id, series_id, season, episode_number, title, duration_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, series_id, season, episode_number, title, duration_minutes, created_at
`

type CreateEpisodeParams struct {
	ID              uuid.UUID `json:"id"`
	SeriesID        uuid.UUID `json:"series_id"`
	Season          int32     `json:"season"`
	EpisodeNumber   int32     `json:"episode_number"`
	Title           string    `json:"title"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.ID,
		arg.SeriesID,
		arg.Season,
		arg.EpisodeNumber,
		arg.Title,
		arg.DurationMinutes,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisode, id)
	return err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, series_id, season, episode_number, title, duration_minutes, created_at FROM episodes WHERE id = $1
`

func (q *Queries) GetEpisode(ctx context.Context, id uuid.UUID) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const listEpisodesBySerie = `-- name: ListEpisodesBySerie :many
SELECT id, series_id, season, episode_number, title, duration_minutes, created_at FROM episodes WHERE series_id = $1 ORDER BY season, episode_number
`

func (q *Queries) ListEpisodesBySerie(ctx context.Context, seriesID uuid.UUID) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesBySerie, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Season,
			&i.EpisodeNumber,
			&i.Title,
			&i.DurationMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes
SET season = $2, episode_number = $3, title = $4, duration_minutes = $5
WHERE id = $1
RETURNING id, series_id, season, episode_number, title, duration_minutes, created_at
`

type UpdateEpisodeParams struct {
	ID              uuid.UUID `json:"id"`
	Season          int32     `json:"season"`
	EpisodeNumber   int32     `json:"episode_number"`
	Title           string    `json:"title"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisode,
		arg.ID,
		arg.Season,
		arg.EpisodeNumber,
		arg.Title,
		arg.DurationMinutes,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Season,
		&i.EpisodeNumber,
		&i.Title,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}
