// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Episode struct {
	ID              uuid.UUID   `json:"id"`
	SerieID         pgtype.Int4 `json:"serie_id"`
	Season          int32       `json:"season"`
	EpisodeNumber   int32       `json:"episode_number"`
	Title           string      `json:"title"`
	DurationMinutes int32       `json:"duration_minutes"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Movie struct {
	ID              uuid.UUID   `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
	ReleaseDate     pgtype.Date `json:"release_date"`
	MaturityRating  string      `json:"maturity_rating"`
	ContentUrl      string      `json:"content_url"`
}

type Profile struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              pgtype.UUID `json:"user_id"`
	Name                string      `json:"name"`
	HasParentalControls bool        `json:"has_parental_controls"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type Review struct {
	ID        int32            `json:"id"`
	ProfileID pgtype.UUID      `json:"profile_id"`
	MovieID   pgtype.UUID      `json:"movie_id"`
	EpisodeID pgtype.UUID      `json:"episode_id"`
	Rating    int32            `json:"rating"`
	Comment   pgtype.Text      `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Series struct {
	ID             int32       `json:"id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	ReleaseDate    pgtype.Date `json:"release_date"`
	MaturityRating pgtype.Text `json:"maturity_rating"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Cpf       string    `json:"cpf"`
	Password  string    `json:"password"`
	Salt      string    `json:"salt"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WatchHistory struct {
	ID                  uuid.UUID        `json:"id"`
	ProfileID           pgtype.UUID      `json:"profile_id"`
	MovieID             pgtype.UUID      `json:"movie_id"`
	EpisodeID           pgtype.UUID      `json:"episode_id"`
	WatchedAt           pgtype.Timestamp `json:"watched_at"`
	LastPositionSeconds pgtype.Int4      `json:"last_position_seconds"`
	IsCompleted         pgtype.Bool      `json:"is_completed"`
}
