// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (id, title, description, duration_minutes, release_date, maturity_rating, content_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, duration_minutes, release_date, maturity_rating, content_url
`

type CreateMovieParams struct {
	ID              uuid.UUID   `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
	ReleaseDate     pgtype.Date `json:"release_date"`
	MaturityRating  string      `json:"maturity_rating"`
	ContentUrl      string      `json:"content_url"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.ReleaseDate,
		arg.MaturityRating,
		arg.ContentUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.ReleaseDate,
		&i.MaturityRating,
		&i.ContentUrl,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, description, duration_minutes, release_date, maturity_rating, content_url FROM movies WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.ReleaseDate,
		&i.MaturityRating,
		&i.ContentUrl,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, description, duration_minutes, release_date, maturity_rating, content_url FROM movies ORDER BY release_date DESC
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.ReleaseDate,
			&i.MaturityRating,
			&i.ContentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = $2, description = $3, duration_minutes = $4, release_date = $5, maturity_rating = $6, content_url = $7
WHERE id = $1
RETURNING id, title, description, duration_minutes, release_date, maturity_rating, content_url
`

type UpdateMovieParams struct {
	ID              uuid.UUID   `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
	ReleaseDate     pgtype.Date `json:"release_date"`
	MaturityRating  string      `json:"maturity_rating"`
	ContentUrl      string      `json:"content_url"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.ReleaseDate,
		arg.MaturityRating,
		arg.ContentUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.ReleaseDate,
		&i.MaturityRating,
		&i.ContentUrl,
	)
	return i, err
}
