// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (profile_id, movie_id, episode_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, movie_id, episode_id, rating, comment, created_at
`

type CreateReviewParams struct {
	ProfileID uuid.UUID   `json:"profile_id"`
	MovieID   pgtype.UUID `json:"movie_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProfileID,
		arg.MovieID,
		arg.EpisodeID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReview = `-- name: GetReview :one
SELECT id, profile_id, movie_id, episode_id, rating, comment, created_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id int32) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewsByEpisode = `-- name: ListReviewsByEpisode :many
SELECT id, profile_id, movie_id, episode_id, rating, comment, created_at FROM reviews WHERE episode_id = $1
`

func (q *Queries) ListReviewsByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.MovieID,
			&i.EpisodeID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByMovie = `-- name: ListReviewsByMovie :many
SELECT id, profile_id, movie_id, episode_id, rating, comment, created_at FROM reviews WHERE movie_id = $1
`

func (q *Queries) ListReviewsByMovie(ctx context.Context, movieID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.MovieID,
			&i.EpisodeID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProfile = `-- name: ListReviewsByProfile :many
SELECT id, profile_id, movie_id, episode_id, rating, comment, created_at FROM reviews WHERE profile_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByProfile(ctx context.Context, profileID uuid.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.MovieID,
			&i.EpisodeID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating = $2, comment = $3
WHERE id = $1
RETURNING id, profile_id, movie_id, episode_id, rating, comment, created_at
`

type UpdateReviewParams struct {
	ID      int32       `json:"id"`
	Rating  int32       `json:"rating"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview, arg.ID, arg.Rating, arg.Comment)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
