// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: series.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSerie = `-- name: CreateSerie :one
INSERT INTO series (title, description, release_date, maturity_rating)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, release_date, maturity_rating
`

type CreateSerieParams struct {
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	ReleaseDate    pgtype.Date `json:"release_date"`
	MaturityRating pgtype.Text `json:"maturity_rating"`
}

func (q *Queries) CreateSerie(ctx context.Context, arg CreateSerieParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSerie,
		arg.Title,
		arg.Description,
		arg.ReleaseDate,
		arg.MaturityRating,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.MaturityRating,
	)
	return i, err
}

const deleteSerie = `-- name: DeleteSerie :exec
DELETE FROM series WHERE id = $1
`

func (q *Queries) DeleteSerie(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSerie, id)
	return err
}

const getSerie = `-- name: GetSerie :one
SELECT id, title, description, release_date, maturity_rating FROM series WHERE id = $1
`

func (q *Queries) GetSerie(ctx context.Context, id int32) (Series, error) {
	row := q.db.QueryRow(ctx, getSerie, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.MaturityRating,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, title, description, release_date, maturity_rating FROM series ORDER BY title
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ReleaseDate,
			&i.MaturityRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSerie = `-- name: UpdateSerie :one
UPDATE series
SET title = $2, description = $3, release_date = $4, maturity_rating = $5
WHERE id = $1
RETURNING id, title, description, release_date, maturity_rating
`

type UpdateSerieParams struct {
	ID             int32       `json:"id"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	ReleaseDate    pgtype.Date `json:"release_date"`
	MaturityRating pgtype.Text `json:"maturity_rating"`
}

func (q *Queries) UpdateSerie(ctx context.Context, arg UpdateSerieParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSerie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ReleaseDate,
		arg.MaturityRating,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.MaturityRating,
	)
	return i, err
}
