// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watch_histories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWatchHistory = `-- name: CreateWatchHistory :one
INSERT INTO watch_histories (id, profile_id, movie_id, episode_id, last_position_seconds, is_completed)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, movie_id, episode_id, watched_at, last_position_seconds, is_completed
`

type CreateWatchHistoryParams struct {
	ID                  uuid.UUID   `json:"id"`
	ProfileID           pgtype.UUID `json:"profile_id"`
	MovieID             pgtype.UUID `json:"movie_id"`
	EpisodeID           pgtype.UUID `json:"episode_id"`
	LastPositionSeconds pgtype.Int4 `json:"last_position_seconds"`
	IsCompleted         pgtype.Bool `json:"is_completed"`
}

func (q *Queries) CreateWatchHistory(ctx context.Context, arg CreateWatchHistoryParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, createWatchHistory,
		arg.ID,
		arg.ProfileID,
		arg.MovieID,
		arg.EpisodeID,
		arg.LastPositionSeconds,
		arg.IsCompleted,
	)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.WatchedAt,
		&i.LastPositionSeconds,
		&i.IsCompleted,
	)
	return i, err
}

const deleteWatchHistory = `-- name: DeleteWatchHistory :exec
DELETE FROM watch_histories WHERE id = $1
`

func (q *Queries) DeleteWatchHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWatchHistory, id)
	return err
}

const getWatchHistory = `-- name: GetWatchHistory :one
SELECT id, profile_id, movie_id, episode_id, watched_at, last_position_seconds, is_completed FROM watch_histories WHERE id = $1
`

func (q *Queries) GetWatchHistory(ctx context.Context, id uuid.UUID) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, getWatchHistory, id)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.WatchedAt,
		&i.LastPositionSeconds,
		&i.IsCompleted,
	)
	return i, err
}

const listWatchHistoryByProfile = `-- name: ListWatchHistoryByProfile :many
SELECT id, profile_id, movie_id, episode_id, watched_at, last_position_seconds, is_completed FROM watch_histories WHERE profile_id = $1 ORDER BY watched_at DESC
`

func (q *Queries) ListWatchHistoryByProfile(ctx context.Context, profileID pgtype.UUID) ([]WatchHistory, error) {
	rows, err := q.db.Query(ctx, listWatchHistoryByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchHistory
	for rows.Next() {
		var i WatchHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.MovieID,
			&i.EpisodeID,
			&i.WatchedAt,
			&i.LastPositionSeconds,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchProgress = `-- name: UpdateWatchProgress :one
UPDATE watch_histories
SET last_position_seconds = $2, is_completed = $3, watched_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, profile_id, movie_id, episode_id, watched_at, last_position_seconds, is_completed
`

type UpdateWatchProgressParams struct {
	ID                  uuid.UUID   `json:"id"`
	LastPositionSeconds pgtype.Int4 `json:"last_position_seconds"`
	IsCompleted         pgtype.Bool `json:"is_completed"`
}

func (q *Queries) UpdateWatchProgress(ctx context.Context, arg UpdateWatchProgressParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, updateWatchProgress, arg.ID, arg.LastPositionSeconds, arg.IsCompleted)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MovieID,
		&i.EpisodeID,
		&i.WatchedAt,
		&i.LastPositionSeconds,
		&i.IsCompleted,
	)
	return i, err
}
