// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countRecommendationsByProfile = `-- name: CountRecommendationsByProfile :one
SELECT COUNT(*) FROM recommendations WHERE profile_id = $1
`

func (q *Queries) CountRecommendationsByProfile(ctx context.Context, profileID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationsByProfile, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO recommendations (id, profile_id, content_id, content_type, score, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, content_id, content_type, score, reason, created_at
`

type CreateRecommendationParams struct {
	ID          uuid.UUID       `json:"id"`
	ProfileID   uuid.UUID       `json:"profile_id"`
	ContentID   uuid.UUID       `json:"content_id"`
	ContentType ContentTypeEnum `json:"content_type"`
	Score       float64         `json:"score"`
	Reason      string          `json:"reason"`
}

func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, createRecommendation,
		arg.ID,
		arg.ProfileID,
		arg.ContentID,
		arg.ContentType,
		arg.Score,
		arg.Reason,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ContentID,
		&i.ContentType,
		&i.Score,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecommendationsByProfile = `-- name: DeleteRecommendationsByProfile :exec
DELETE FROM recommendations WHERE profile_id = $1
`

func (q *Queries) DeleteRecommendationsByProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecommendationsByProfile, profileID)
	return err
}

const listRecommendationsByProfile = `-- name: ListRecommendationsByProfile :many
SELECT id, profile_id, content_id, content_type, score, reason, created_at FROM recommendations
WHERE profile_id = $1
ORDER BY score DESC
LIMIT $2
`

type ListRecommendationsByProfileParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int       `json:"limit"`
}

func (q *Queries) ListRecommendationsByProfile(ctx context.Context, arg ListRecommendationsByProfileParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByProfile, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ContentID,
			&i.ContentType,
			&i.Score,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
