package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"errors"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
)

var ErrInvalidEmailOrPassword = errors.New("invalid email and/or Password")

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (string, error) {
	userID, err := r.AuthService.Login(ctx, *input)
	if err != nil {
		r.Logger.Error("failed to make login", slog.Any("error", err))
		return "", ErrInvalidEmailOrPassword
	}

	err = r.Sessions.RenewToken(ctx)
	if err != nil {
		r.Logger.Error("failed to renew user token", slog.Any("error", err))
		return "", errors.New("failed to make login, try again after")
	}

	r.Sessions.Put(ctx, "AuthenticatedUserID", userID)

	return "user authenticated successfully", nil
}
