package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88
import (
	"context"
	"errors"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/apperror"
	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (string, error) {
	userID, err := r.AuthService.Login(ctx, *input)
	if err != nil {
		r.Logger.Error("failed to make login", slog.Any("error", err))

		var validationErr *apperror.ValidationError
		if errors.As(err, &validationErr) {
			return "", handleError(err)
		}

		return "", ErrInvalidEmailOrPassword
	}

	err = r.Sessions.RenewToken(ctx)
	if err != nil {
		r.Logger.Error("failed to renew user token", slog.Any("error", err))
		return "", gqlerror.Errorf("error logging in, try again after")
	}

	r.Sessions.Put(ctx, shared.SessionUserIDKey, userID)

	return "user authenticated successfully", nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (string, error) {
	if !r.Sessions.Exists(ctx, shared.SessionUserIDKey) {
		return "", ErrUserNotLoggedIn
	}

	return "user successfully logged out", nil
}
