package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/google/uuid"
)

// CreateEpisode is the resolver for the createEpisode field.
func (r *mutationResolver) CreateEpisode(ctx context.Context, input model.CreateEpisodeInput) (*model.Episode, error) {
	return r.EpisodeService.CreateEpisode(ctx, input)
}

// UpdateEpisode is the resolver for the updateEpisode field.
func (r *mutationResolver) UpdateEpisode(ctx context.Context, id string, input model.UpdateEpisodeInput) (*model.Episode, error) {
	episodeID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.EpisodeService.UpdateEpisode(ctx, episodeID, input)
}

// DeleteEpisode is the resolver for the deleteEpisode field.
func (r *mutationResolver) DeleteEpisode(ctx context.Context, id string) (bool, error) {
	episodeID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	err = r.EpisodeService.DeleteEpisode(ctx, episodeID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetEpisode is the resolver for the getEpisode field.
func (r *queryResolver) GetEpisode(ctx context.Context, id string) (*model.Episode, error) {
	episodeID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.EpisodeService.GetEpisode(ctx, episodeID)
}

// ListEpisodes is the resolver for the listEpisodes field.
func (r *queryResolver) ListEpisodes(ctx context.Context, serieID int32) ([]*model.Episode, error) {
	return r.EpisodeService.ListEpisodes(ctx, serieID)
}
