package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Reviews is the resolver for the reviews field.
func (r *episodeResolver) Reviews(ctx context.Context, obj *model.Episode) ([]*model.Review, error) {
	reviews, err := r.ReviewService.ListReviewsByEpisode(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("failed to list reviews", slog.Any("error", err))
		return nil, handleError(err)
	}

	return reviews, nil
}

// CreateEpisode is the resolver for the createEpisode field.
func (r *mutationResolver) CreateEpisode(ctx context.Context, input model.CreateEpisodeInput) (*model.Episode, error) {
	episode, err := r.EpisodeService.CreateEpisode(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create episode", slog.Any("error", err))
		return nil, handleError(err)
	}

	return episode, nil
}

// UpdateEpisode is the resolver for the updateEpisode field.
func (r *mutationResolver) UpdateEpisode(ctx context.Context, id uuid.UUID, input model.UpdateEpisodeInput) (*model.Episode, error) {
	episode, err := r.EpisodeService.UpdateEpisode(ctx, id, input)
	if err != nil {
		r.Logger.Error("failed to update episode", slog.Any("error", err))
		return nil, handleError(err)
	}

	return episode, nil
}

// DeleteEpisode is the resolver for the deleteEpisode field.
func (r *mutationResolver) DeleteEpisode(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.EpisodeService.DeleteEpisode(ctx, id)
	if err != nil {
		r.Logger.Error("failed to delete episode", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetEpisode is the resolver for the getEpisode field.
func (r *queryResolver) GetEpisode(ctx context.Context, id uuid.UUID) (*model.Episode, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to create watch history")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	episode, err := r.EpisodeService.GetEpisode(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to get episode", slog.Any("error", err))
		return nil, handleError(err)
	}

	return episode, nil
}

// ListEpisodes is the resolver for the listEpisodes field.
func (r *queryResolver) ListEpisodes(ctx context.Context, seriesID uuid.UUID) ([]*model.Episode, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to create watch history")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	episodes, err := r.EpisodeService.ListEpisodesBySeries(ctx, seriesID, profileID)
	if err != nil {
		r.Logger.Error("failed to list all episodes from a series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return episodes, nil
}

// Episode returns graph.EpisodeResolver implementation.
func (r *Resolver) Episode() graph.EpisodeResolver { return &episodeResolver{r} }

type episodeResolver struct{ *Resolver }
