package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Reviews is the resolver for the reviews field.
func (r *movieResolver) Reviews(ctx context.Context, obj *model.Movie) ([]*model.Review, error) {
	panic(fmt.Errorf("not implemented: Reviews - reviews"))
}

// CreateMovie is the resolver for the createMovie field.
func (r *mutationResolver) CreateMovie(ctx context.Context, input model.CreateMovieInput) (*model.Movie, error) {
	movie, err := r.MovieService.CreateMovie(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create movie", slog.Any("error", err))
		return nil, handleError(err)
	}

	return movie, nil
}

// UpdateMovie is the resolver for the updateMovie field.
func (r *mutationResolver) UpdateMovie(ctx context.Context, id uuid.UUID, input model.UpdateMovieInput) (*model.Movie, error) {
	movie, err := r.MovieService.UpdateMovie(ctx, id, input)
	if err != nil {
		r.Logger.Error("failed to update movie", slog.Any("error", err))
		return nil, handleError(err)
	}

	return movie, nil
}

// DeleteMovie is the resolver for the deleteMovie field.
func (r *mutationResolver) DeleteMovie(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.MovieService.DeleteMovie(ctx, id)
	if err != nil {
		r.Logger.Error("failed to delete movie", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetMovie is the resolver for the getMovie field.
func (r *queryResolver) GetMovie(ctx context.Context, id uuid.UUID) (*model.Movie, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to get movie")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	movie, err := r.MovieService.GetMovie(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to get movie", slog.Any("error", err))
		return nil, handleError(err)
	}

	return movie, nil
}

// ListMovies is the resolver for the listMovies field.
func (r *queryResolver) ListMovies(ctx context.Context) ([]*model.Movie, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to list movies")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	movies, err := r.MovieService.ListMovies(ctx, profileID)
	if err != nil {
		r.Logger.Error("failed to get all movies", slog.Any("error", err))
		return nil, handleError(err)
	}

	return movies, nil
}

// Movie returns graph.MovieResolver implementation.
func (r *Resolver) Movie() graph.MovieResolver { return &movieResolver{r} }

type movieResolver struct{ *Resolver }
