package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/google/uuid"
)

// CreateProfile is the resolver for the createProfile field.
// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.CreateProfileInput) (*model.Profile, error) {
	return r.ProfileService.CreateProfile(ctx, input)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id string, input model.UpdateProfileInput) (*model.Profile, error) {
	profileID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.ProfileService.UpdateProfile(ctx, profileID, input)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, id string) (bool, error) {
	profileID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	err = r.ProfileService.DeleteProfile(ctx, profileID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetProfile is the resolver for the getProfile field.
// GetProfile is the resolver for the getProfile field.
func (r *queryResolver) GetProfile(ctx context.Context, id string) (*model.Profile, error) {
	profileID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.ProfileService.GetProfile(ctx, profileID)
}

// ListProfiles is the resolver for the listProfiles field.
func (r *queryResolver) ListProfiles(ctx context.Context, userID string) ([]*model.Profile, error) {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return nil, err
	}
	return r.ProfileService.ListProfiles(ctx, uid)
}
