package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to create review")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	review, err := r.ReviewService.CreateReview(ctx, input, profileID)
	if err != nil {
		r.Logger.Error("failed to create review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id uuid.UUID, input model.UpdateReviewInput) (*model.Review, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to update review")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	review, err := r.ReviewService.UpdateReview(ctx, id, input, profileID)
	if err != nil {
		r.Logger.Error("failed to update review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to delete review")
		return false, gqlerror.Errorf("invalid profile ID")
	}

	err := r.ReviewService.DeleteReview(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to delete review", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetReview is the resolver for the getReview field.
func (r *queryResolver) GetReview(ctx context.Context, id uuid.UUID) (*model.Review, error) {
	review, err := r.ReviewService.GetReview(ctx, id)
	if err != nil {
		r.Logger.Error("failed to get review", slog.Any("error", err))
		return nil, handleError(err)
	}

	return review, nil
}

// ListReviews is the resolver for the listReviews field.
func (r *queryResolver) ListReviews(ctx context.Context) ([]*model.Review, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to list reviews")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	reviews, err := r.ReviewService.ListReviewsByProfile(ctx, profileID)
	if err != nil {
		r.Logger.Error("failed to list reviews", slog.Any("error", err))
		return nil, handleError(err)
	}

	return reviews, nil
}
