package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/google/uuid"
)

// CreateReview is the resolver for the createReview field.
// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	return r.ReviewService.CreateReview(ctx, input)
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id string, input model.UpdateReviewInput) (*model.Review, error) {
	reviewID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.ReviewService.UpdateReview(ctx, int32(reviewID), input)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id string) (bool, error) {
	reviewID, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}
	err = r.ReviewService.DeleteReview(ctx, int32(reviewID))
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetReview is the resolver for the getReview field.
func (r *queryResolver) GetReview(ctx context.Context, id string) (*model.Review, error) {
	reviewID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.ReviewService.GetReview(ctx, int32(reviewID))
}

// ListReviews is the resolver for the listReviews field.
func (r *queryResolver) ListReviews(ctx context.Context, profileID string) ([]*model.Review, error) {
	pid, err := uuid.Parse(profileID)
	if err != nil {
		return nil, err
	}
	return r.ReviewService.ListReviews(ctx, pid)
}
