package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input model.CreateSeriesInput) (*model.Series, error) {
	s, err := r.SeriesService.CreateSeries(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// UpdateSeries is the resolver for the updateSeries field.
func (r *mutationResolver) UpdateSeries(ctx context.Context, id string, input model.UpdateSeriesInput) (*model.Series, error) {
	seriesID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse series id to update it", slog.Any("error", err))
		return nil, gqlerror.Errorf("invalid series ID")
	}

	s, err := r.SeriesService.UpdateSeries(ctx, seriesID, input)
	if err != nil {
		r.Logger.Error("failed to update series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// DeleteSeries is the resolver for the deleteSeries field.
func (r *mutationResolver) DeleteSeries(ctx context.Context, id string) (bool, error) {
	seriesID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse series id to delete it", slog.Any("error", err))
		return false, gqlerror.Errorf("invalid series ID")
	}

	err = r.SeriesService.DeleteSeries(ctx, seriesID)
	if err != nil {
		r.Logger.Error("failed to delete series", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetSeries is the resolver for the getSeries field.
func (r *queryResolver) GetSeries(ctx context.Context, id string) (*model.Series, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to get series")
		return nil, gqlerror.Errorf("invalid profile ID")
	}
	seriesID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse series id to get it", slog.Any("error", err))
		return nil, gqlerror.Errorf("invalid series ID")
	}

	s, err := r.SeriesService.GetSeries(ctx, seriesID, profileID)
	if err != nil {
		r.Logger.Error("failed to get series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return s, nil
}

// ListSeries is the resolver for the listSeries field.
func (r *queryResolver) ListSeries(ctx context.Context) ([]*model.Series, error) {
	profileID, ok := r.Sessions.Get(ctx, shared.SessionProfileIDKey).(uuid.UUID)
	if !ok {
		r.Logger.Error("failed to get profile id to create watch history")
		return nil, gqlerror.Errorf("invalid profile ID")
	}

	series, err := r.SeriesService.ListSeries(ctx, profileID)
	if err != nil {
		r.Logger.Error("failed to list all series", slog.Any("error", err))
		return nil, handleError(err)
	}

	return series, nil
}
