package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
)

// CreateSeries is the resolver for the createSeries field.
func (r *mutationResolver) CreateSeries(ctx context.Context, input model.CreateSeriesInput) (*model.Series, error) {
	return r.SeriesService.CreateSeries(ctx, input)
}

// UpdateSeries is the resolver for the updateSeries field.
func (r *mutationResolver) UpdateSeries(ctx context.Context, id string, input model.UpdateSeriesInput) (*model.Series, error) {
	seriesID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.SeriesService.UpdateSeries(ctx, int32(seriesID), input)
}

// DeleteSeries is the resolver for the deleteSeries field.
func (r *mutationResolver) DeleteSeries(ctx context.Context, id string) (bool, error) {
	seriesID, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}
	err = r.SeriesService.DeleteSeries(ctx, int32(seriesID))
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetSeries is the resolver for the getSeries field.
func (r *queryResolver) GetSeries(ctx context.Context, id string) (*model.Series, error) {
	seriesID, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.SeriesService.GetSeries(ctx, int32(seriesID))
}

// ListSeries is the resolver for the listSeries field.
func (r *queryResolver) ListSeries(ctx context.Context) ([]*model.Series, error) {
	return r.SeriesService.ListSeries(ctx)
}
