package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.UserService.CreateUser(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse user id to update it", slog.Any("error", err))
		return nil, gqlerror.Errorf("invalid user ID")
	}

	sessionUserID, ok := r.Sessions.Get(ctx, shared.SessionUserIDKey).(uuid.UUID)
	if !ok || sessionUserID != userID {
		return nil, gqlerror.Errorf("access denied")
	}

	user, err := r.UserService.UpdateUser(ctx, userID, input)
	if err != nil {
		r.Logger.Error("failed to update user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse user id to delete it", slog.Any("error", err))
		return false, gqlerror.Errorf("invalid user ID")
	}

	sessionUserID, ok := r.Sessions.Get(ctx, shared.SessionUserIDKey).(uuid.UUID)
	if !ok || sessionUserID != userID {
		return false, gqlerror.Errorf("access denied")
	}

	err = r.UserService.DeleteUser(ctx, userID)
	if err != nil {
		r.Logger.Error("failed to delete user", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		r.Logger.Error("failed to parse user id to get it", slog.Any("error", err))
		return nil, gqlerror.Errorf("invalid user ID")
	}

	user, err := r.UserService.GetUser(ctx, userID)
	if err != nil {
		r.Logger.Error("failed to get user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.ListUsers(ctx)
	if err != nil {
		r.Logger.Error("failed to list all users", slog.Any("error", err))
		return nil, handleError(err)
	}

	return users, nil
}
