package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph"
	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/ecbDeveloper/netflix-architecture/internal/shared"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.UserService.CreateUser(ctx, input)
	if err != nil {
		r.Logger.Error("failed to create user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input model.UpdateUserInput) (*model.User, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user id to update user", slog.Any("error", err))
		return nil, handleError(err)
	}

	if sessionUserID != id {
		return nil, gqlerror.Errorf("access denied")
	}

	user, err := r.UserService.UpdateUser(ctx, id, input)
	if err != nil {
		r.Logger.Error("failed to update user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user id to delete user", slog.Any("error", err))
		return false, handleError(err)
	}

	if sessionUserID != id {
		return false, gqlerror.Errorf("you can't delete other users")
	}

	err = r.UserService.DeleteUser(ctx, id)
	if err != nil {
		r.Logger.Error("failed to delete user", slog.Any("error", err))
		return false, handleError(err)
	}

	if err := r.Sessions.Destroy(ctx); err != nil {
		r.Logger.Error("failed to destroy session", slog.Any("error", err))
		return false, gqlerror.Errorf("error deleting user, try again later")
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id uuid.UUID) (*model.User, error) {
	sessionUserID, err := r.getUserIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user id to get user", slog.Any("error", err))
		return nil, handleError(err)
	}

	sessionRoleID, err := r.getUserRoleIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get user role id to get user", slog.Any("error", err))
		return nil, handleError(err)
	}

	if sessionUserID != id && sessionRoleID != shared.DBRoleAdmin {
		r.Logger.Error("user is not authorized to get user")
		return nil, gqlerror.Errorf("you can't access other users data")
	}

	user, err := r.UserService.GetUser(ctx, id)
	if err != nil {
		r.Logger.Error("failed to get user", slog.Any("error", err))
		return nil, handleError(err)
	}

	return user, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.ListUsers(ctx)
	if err != nil {
		r.Logger.Error("failed to list all users", slog.Any("error", err))
		return nil, handleError(err)
	}

	return users, nil
}

// Profiles is the resolver for the profiles field.
func (r *userResolver) Profiles(ctx context.Context, obj *model.User) ([]*model.Profile, error) {
	profiles, err := r.ProfileService.ListProfilesByUser(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("failed to list profiles", slog.Any("error", err))
		return nil, handleError(err)
	}

	return profiles, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
