package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/google/uuid"
)

// CreateWatchHistory is the resolver for the createWatchHistory field.
func (r *mutationResolver) CreateWatchHistory(ctx context.Context, input model.CreateWatchHistoryInput) (*model.WatchHistory, error) {
	return r.WatchhistoryService.CreateWatchHistory(ctx, input)
}

// UpdateWatchHistory is the resolver for the updateWatchHistory field.
func (r *mutationResolver) UpdateWatchHistory(ctx context.Context, id string, input model.UpdateWatchHistoryInput) (*model.WatchHistory, error) {
	whID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.WatchhistoryService.UpdateWatchHistory(ctx, whID, input)
}

// DeleteWatchHistory is the resolver for the deleteWatchHistory field.
func (r *mutationResolver) DeleteWatchHistory(ctx context.Context, id string) (bool, error) {
	whID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	err = r.WatchhistoryService.DeleteWatchHistory(ctx, whID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetWatchHistory is the resolver for the getWatchHistory field.
func (r *queryResolver) GetWatchHistory(ctx context.Context, id string) (*model.WatchHistory, error) {
	whID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.WatchhistoryService.GetWatchHistory(ctx, whID)
}

// ListWatchHistories is the resolver for the listWatchHistories field.
func (r *queryResolver) ListWatchHistories(ctx context.Context, profileID string) ([]*model.WatchHistory, error) {
	pid, err := uuid.Parse(profileID)
	if err != nil {
		return nil, err
	}
	return r.WatchhistoryService.ListWatchHistories(ctx, pid)
}
