package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"log/slog"

	"github.com/ecbDeveloper/netflix-architecture/internal/graph/model"
	"github.com/google/uuid"
)

// CreateWatchHistory is the resolver for the createWatchHistory field.
func (r *mutationResolver) CreateWatchHistory(ctx context.Context, input model.CreateWatchHistoryInput) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to create watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	wh, err := r.WatchHistoryService.CreateWatchHistory(ctx, input, profileID)
	if err != nil {
		r.Logger.Error("failed to create watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	return wh, nil
}

// UpdateWatchHistory is the resolver for the updateWatchHistory field.
func (r *mutationResolver) UpdateWatchHistory(ctx context.Context, id uuid.UUID, input model.UpdateWatchHistoryInput) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to update watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	wh, err := r.WatchHistoryService.UpdateWatchHistory(ctx, id, input, profileID)
	if err != nil {
		r.Logger.Error("failed to update watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	return wh, nil
}

// DeleteWatchHistory is the resolver for the deleteWatchHistory field.
func (r *mutationResolver) DeleteWatchHistory(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to delete watch history", slog.Any("error", err))
		return false, handleError(err)
	}

	err = r.WatchHistoryService.DeleteWatchHistory(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to delete watch history", slog.Any("error", err))
		return false, handleError(err)
	}

	return true, nil
}

// GetWatchHistory is the resolver for the getWatchHistory field.
func (r *queryResolver) GetWatchHistory(ctx context.Context, id uuid.UUID) (*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to get one watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	wh, err := r.WatchHistoryService.GetWatchHistory(ctx, id, profileID)
	if err != nil {
		r.Logger.Error("failed to get watch history", slog.Any("error", err))
		return nil, handleError(err)
	}

	return wh, nil
}

// ListWatchHistories is the resolver for the listWatchHistories field.
func (r *queryResolver) ListWatchHistories(ctx context.Context) ([]*model.WatchHistory, error) {
	profileID, err := r.getProfileIDFromSession(ctx)
	if err != nil {
		r.Logger.Error("failed to get profile id to list watch histories", slog.Any("error", err))
		return nil, handleError(err)
	}

	watchHistories, err := r.WatchHistoryService.ListWatchHistories(ctx, profileID)
	if err != nil {
		r.Logger.Error("failed to list watch histories", slog.Any("error", err))
		return nil, handleError(err)
	}

	return watchHistories, nil
}
