// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/history/history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordWatchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProfileId           string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	MovieId             *string                `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3,oneof" json:"movie_id,omitempty"`
	EpisodeId           *string                `protobuf:"bytes,3,opt,name=episode_id,json=episodeId,proto3,oneof" json:"episode_id,omitempty"`
	LastPositionSeconds *int32                 `protobuf:"varint,4,opt,name=last_position_seconds,json=lastPositionSeconds,proto3,oneof" json:"last_position_seconds,omitempty"`
	IsCompleted         *bool                  `protobuf:"varint,5,opt,name=is_completed,json=isCompleted,proto3,oneof" json:"is_completed,omitempty"`
	GenreId             *int32                 `protobuf:"varint,6,opt,name=genre_id,json=genreId,proto3,oneof" json:"genre_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecordWatchRequest) Reset() {
	*x = RecordWatchRequest{}
	mi := &file_proto_history_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWatchRequest) ProtoMessage() {}

func (x *RecordWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWatchRequest.ProtoReflect.Descriptor instead.
func (*RecordWatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{0}
}

func (x *RecordWatchRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *RecordWatchRequest) GetMovieId() string {
	if x != nil && x.MovieId != nil {
		return *x.MovieId
	}
	return ""
}

func (x *RecordWatchRequest) GetEpisodeId() string {
	if x != nil && x.EpisodeId != nil {
		return *x.EpisodeId
	}
	return ""
}

func (x *RecordWatchRequest) GetLastPositionSeconds() int32 {
	if x != nil && x.LastPositionSeconds != nil {
		return *x.LastPositionSeconds
	}
	return 0
}

func (x *RecordWatchRequest) GetIsCompleted() bool {
	if x != nil && x.IsCompleted != nil {
		return *x.IsCompleted
	}
	return false
}

func (x *RecordWatchRequest) GetGenreId() int32 {
	if x != nil && x.GenreId != nil {
		return *x.GenreId
	}
	return 0
}

type GetWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchHistoryRequest) Reset() {
	*x = GetWatchHistoryRequest{}
	mi := &file_proto_history_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchHistoryRequest) ProtoMessage() {}

func (x *GetWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetWatchHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchHistoryRequest) Reset() {
	*x = ListWatchHistoryRequest{}
	mi := &file_proto_history_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchHistoryRequest) ProtoMessage() {}

func (x *ListWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{2}
}

func (x *ListWatchHistoryRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type UpdateWatchProgressRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastPositionSeconds *int32                 `protobuf:"varint,2,opt,name=last_position_seconds,json=lastPositionSeconds,proto3,oneof" json:"last_position_seconds,omitempty"`
	IsCompleted         *bool                  `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3,oneof" json:"is_completed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateWatchProgressRequest) Reset() {
	*x = UpdateWatchProgressRequest{}
	mi := &file_proto_history_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWatchProgressRequest) ProtoMessage() {}

func (x *UpdateWatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWatchProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateWatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWatchProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWatchProgressRequest) GetLastPositionSeconds() int32 {
	if x != nil && x.LastPositionSeconds != nil {
		return *x.LastPositionSeconds
	}
	return 0
}

func (x *UpdateWatchProgressRequest) GetIsCompleted() bool {
	if x != nil && x.IsCompleted != nil {
		return *x.IsCompleted
	}
	return false
}

type DeleteWatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWatchHistoryRequest) Reset() {
	*x = DeleteWatchHistoryRequest{}
	mi := &file_proto_history_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWatchHistoryRequest) ProtoMessage() {}

func (x *DeleteWatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteWatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWatchHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWatchHistoryResponse) Reset() {
	*x = DeleteWatchHistoryResponse{}
	mi := &file_proto_history_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWatchHistoryResponse) ProtoMessage() {}

func (x *DeleteWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWatchHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchHistoryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileId           string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	MovieId             *string                `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3,oneof" json:"movie_id,omitempty"`
	EpisodeId           *string                `protobuf:"bytes,4,opt,name=episode_id,json=episodeId,proto3,oneof" json:"episode_id,omitempty"`
	WatchedAt           string                 `protobuf:"bytes,5,opt,name=watched_at,json=watchedAt,proto3" json:"watched_at,omitempty"`
	LastPositionSeconds int32                  `protobuf:"varint,6,opt,name=last_position_seconds,json=lastPositionSeconds,proto3" json:"last_position_seconds,omitempty"`
	IsCompleted         bool                   `protobuf:"varint,7,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	GenreId             int32                  `protobuf:"varint,8,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WatchHistoryResponse) Reset() {
	*x = WatchHistoryResponse{}
	mi := &file_proto_history_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchHistoryResponse) ProtoMessage() {}

func (x *WatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*WatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{6}
}

func (x *WatchHistoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchHistoryResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *WatchHistoryResponse) GetMovieId() string {
	if x != nil && x.MovieId != nil {
		return *x.MovieId
	}
	return ""
}

func (x *WatchHistoryResponse) GetEpisodeId() string {
	if x != nil && x.EpisodeId != nil {
		return *x.EpisodeId
	}
	return ""
}

func (x *WatchHistoryResponse) GetWatchedAt() string {
	if x != nil {
		return x.WatchedAt
	}
	return ""
}

func (x *WatchHistoryResponse) GetLastPositionSeconds() int32 {
	if x != nil {
		return x.LastPositionSeconds
	}
	return 0
}

func (x *WatchHistoryResponse) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *WatchHistoryResponse) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

type ListWatchHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Histories     []*WatchHistoryResponse `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchHistoryResponse) Reset() {
	*x = ListWatchHistoryResponse{}
	mi := &file_proto_history_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchHistoryResponse) ProtoMessage() {}

func (x *ListWatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListWatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{7}
}

func (x *ListWatchHistoryResponse) GetHistories() []*WatchHistoryResponse {
	if x != nil {
		return x.Histories
	}
	return nil
}

type GetMostWatchedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMostWatchedRequest) Reset() {
	*x = GetMostWatchedRequest{}
	mi := &file_proto_history_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMostWatchedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostWatchedRequest) ProtoMessage() {}

func (x *GetMostWatchedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostWatchedRequest.ProtoReflect.Descriptor instead.
func (*GetMostWatchedRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{8}
}

func (x *GetMostWatchedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MostWatchedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "movie" or "episode"
	GenreId       int32                  `protobuf:"varint,3,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	WatchCount    int64                  `protobuf:"varint,4,opt,name=watch_count,json=watchCount,proto3" json:"watch_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostWatchedItem) Reset() {
	*x = MostWatchedItem{}
	mi := &file_proto_history_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostWatchedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostWatchedItem) ProtoMessage() {}

func (x *MostWatchedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostWatchedItem.ProtoReflect.Descriptor instead.
func (*MostWatchedItem) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{9}
}

func (x *MostWatchedItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *MostWatchedItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MostWatchedItem) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *MostWatchedItem) GetWatchCount() int64 {
	if x != nil {
		return x.WatchCount
	}
	return 0
}

type MostWatchedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MostWatchedItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostWatchedResponse) Reset() {
	*x = MostWatchedResponse{}
	mi := &file_proto_history_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostWatchedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostWatchedResponse) ProtoMessage() {}

func (x *MostWatchedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostWatchedResponse.ProtoReflect.Descriptor instead.
func (*MostWatchedResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{10}
}

func (x *MostWatchedResponse) GetItems() []*MostWatchedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRecentlyWatchedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentlyWatchedRequest) Reset() {
	*x = GetRecentlyWatchedRequest{}
	mi := &file_proto_history_history_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentlyWatchedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentlyWatchedRequest) ProtoMessage() {}

func (x *GetRecentlyWatchedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_history_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentlyWatchedRequest.ProtoReflect.Descriptor instead.
func (*GetRecentlyWatchedRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_history_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecentlyWatchedRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *GetRecentlyWatchedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_history_history_proto protoreflect.FileDescriptor

const file_proto_history_history_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/history/history.proto\x12\ahistory\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\x12RecordWatchRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1e\n" +
	"\bmovie_id\x18\x02 \x01(\tH\x00R\amovieId\x88\x01\x01\x12\"\n" +
	"\n" +
	"episode_id\x18\x03 \x01(\tH\x01R\tepisodeId\x88\x01\x01\x127\n" +
	"\x15last_position_seconds\x18\x04 \x01(\x05H\x02R\x13lastPositionSeconds\x88\x01\x01\x12&\n" +
	"\fis_completed\x18\x05 \x01(\bH\x03R\visCompleted\x88\x01\x01\x12\x1e\n" +
	"\bgenre_id\x18\x06 \x01(\x05H\x04R\agenreId\x88\x01\x01B\v\n" +
	"\t_movie_idB\r\n" +
	"\v_episode_idB\x18\n" +
	"\x16_last_position_secondsB\x0f\n" +
	"\r_is_completedB\v\n" +
	"\t_genre_id\"(\n" +
	"\x16GetWatchHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x17ListWatchHistoryRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\xb8\x01\n" +
	"\x1aUpdateWatchProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x15last_position_seconds\x18\x02 \x01(\x05H\x00R\x13lastPositionSeconds\x88\x01\x01\x12&\n" +
	"\fis_completed\x18\x03 \x01(\bH\x01R\visCompleted\x88\x01\x01B\x18\n" +
	"\x16_last_position_secondsB\x0f\n" +
	"\r_is_completed\"+\n" +
	"\x19DeleteWatchHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1aDeleteWatchHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb6\x02\n" +
	"\x14WatchHistoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1e\n" +
	"\bmovie_id\x18\x03 \x01(\tH\x00R\amovieId\x88\x01\x01\x12\"\n" +
	"\n" +
	"episode_id\x18\x04 \x01(\tH\x01R\tepisodeId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"watched_at\x18\x05 \x01(\tR\twatchedAt\x122\n" +
	"\x15last_position_seconds\x18\x06 \x01(\x05R\x13lastPositionSeconds\x12!\n" +
	"\fis_completed\x18\a \x01(\bR\visCompleted\x12\x19\n" +
	"\bgenre_id\x18\b \x01(\x05R\agenreIdB\v\n" +
	"\t_movie_idB\r\n" +
	"\v_episode_id\"W\n" +
	"\x18ListWatchHistoryResponse\x12;\n" +
	"\thistories\x18\x01 \x03(\v2\x1d.history.WatchHistoryResponseR\thistories\"-\n" +
	"\x15GetMostWatchedRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x8f\x01\n" +
	"\x0fMostWatchedItem\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x19\n" +
	"\bgenre_id\x18\x03 \x01(\x05R\agenreId\x12\x1f\n" +
	"\vwatch_count\x18\x04 \x01(\x03R\n" +
	"watchCount\"E\n" +
	"\x13MostWatchedResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.history.MostWatchedItemR\x05items\"P\n" +
	"\x19GetRecentlyWatchedRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\xee\x04\n" +
	"\x0eHistoryService\x12I\n" +
	"\vRecordWatch\x12\x1b.history.RecordWatchRequest\x1a\x1d.history.WatchHistoryResponse\x12Q\n" +
	"\x0fGetWatchHistory\x12\x1f.history.GetWatchHistoryRequest\x1a\x1d.history.WatchHistoryResponse\x12W\n" +
	"\x10ListWatchHistory\x12 .history.ListWatchHistoryRequest\x1a!.history.ListWatchHistoryResponse\x12Y\n" +
	"\x13UpdateWatchProgress\x12#.history.UpdateWatchProgressRequest\x1a\x1d.history.WatchHistoryResponse\x12]\n" +
	"\x12DeleteWatchHistory\x12\".history.DeleteWatchHistoryRequest\x1a#.history.DeleteWatchHistoryResponse\x12N\n" +
	"\x0eGetMostWatched\x12\x1e.history.GetMostWatchedRequest\x1a\x1c.history.MostWatchedResponse\x12[\n" +
	"\x12GetRecentlyWatched\x12\".history.GetRecentlyWatchedRequest\x1a!.history.ListWatchHistoryResponseB<Z:github.com/ecbDeveloper/netflix-architecture/proto/historyb\x06proto3"

var (
	file_proto_history_history_proto_rawDescOnce sync.Once
	file_proto_history_history_proto_rawDescData []byte
)

func file_proto_history_history_proto_rawDescGZIP() []byte {
	file_proto_history_history_proto_rawDescOnce.Do(func() {
		file_proto_history_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_history_history_proto_rawDesc), len(file_proto_history_history_proto_rawDesc)))
	})
	return file_proto_history_history_proto_rawDescData
}

var file_proto_history_history_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_history_history_proto_goTypes = []any{
	(*RecordWatchRequest)(nil),         // 0: history.RecordWatchRequest
	(*GetWatchHistoryRequest)(nil),     // 1: history.GetWatchHistoryRequest
	(*ListWatchHistoryRequest)(nil),    // 2: history.ListWatchHistoryRequest
	(*UpdateWatchProgressRequest)(nil), // 3: history.UpdateWatchProgressRequest
	(*DeleteWatchHistoryRequest)(nil),  // 4: history.DeleteWatchHistoryRequest
	(*DeleteWatchHistoryResponse)(nil), // 5: history.DeleteWatchHistoryResponse
	(*WatchHistoryResponse)(nil),       // 6: history.WatchHistoryResponse
	(*ListWatchHistoryResponse)(nil),   // 7: history.ListWatchHistoryResponse
	(*GetMostWatchedRequest)(nil),      // 8: history.GetMostWatchedRequest
	(*MostWatchedItem)(nil),            // 9: history.MostWatchedItem
	(*MostWatchedResponse)(nil),        // 10: history.MostWatchedResponse
	(*GetRecentlyWatchedRequest)(nil),  // 11: history.GetRecentlyWatchedRequest
}
var file_proto_history_history_proto_depIdxs = []int32{
	6,  // 0: history.ListWatchHistoryResponse.histories:type_name -> history.WatchHistoryResponse
	9,  // 1: history.MostWatchedResponse.items:type_name -> history.MostWatchedItem
	0,  // 2: history.HistoryService.RecordWatch:input_type -> history.RecordWatchRequest
	1,  // 3: history.HistoryService.GetWatchHistory:input_type -> history.GetWatchHistoryRequest
	2,  // 4: history.HistoryService.ListWatchHistory:input_type -> history.ListWatchHistoryRequest
	3,  // 5: history.HistoryService.UpdateWatchProgress:input_type -> history.UpdateWatchProgressRequest
	4,  // 6: history.HistoryService.DeleteWatchHistory:input_type -> history.DeleteWatchHistoryRequest
	8,  // 7: history.HistoryService.GetMostWatched:input_type -> history.GetMostWatchedRequest
	11, // 8: history.HistoryService.GetRecentlyWatched:input_type -> history.GetRecentlyWatchedRequest
	6,  // 9: history.HistoryService.RecordWatch:output_type -> history.WatchHistoryResponse
	6,  // 10: history.HistoryService.GetWatchHistory:output_type -> history.WatchHistoryResponse
	7,  // 11: history.HistoryService.ListWatchHistory:output_type -> history.ListWatchHistoryResponse
	6,  // 12: history.HistoryService.UpdateWatchProgress:output_type -> history.WatchHistoryResponse
	5,  // 13: history.HistoryService.DeleteWatchHistory:output_type -> history.DeleteWatchHistoryResponse
	10, // 14: history.HistoryService.GetMostWatched:output_type -> history.MostWatchedResponse
	7,  // 15: history.HistoryService.GetRecentlyWatched:output_type -> history.ListWatchHistoryResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_history_history_proto_init() }
func file_proto_history_history_proto_init() {
	if File_proto_history_history_proto != nil {
		return
	}
	file_proto_history_history_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_history_history_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_history_history_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_history_history_proto_rawDesc), len(file_proto_history_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_history_history_proto_goTypes,
		DependencyIndexes: file_proto_history_history_proto_depIdxs,
		MessageInfos:      file_proto_history_history_proto_msgTypes,
	}.Build()
	File_proto_history_history_proto = out.File
	file_proto_history_history_proto_goTypes = nil
	file_proto_history_history_proto_depIdxs = nil
}
