// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/history/history.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_RecordWatch_FullMethodName         = "/history.HistoryService/RecordWatch"
	HistoryService_GetWatchHistory_FullMethodName     = "/history.HistoryService/GetWatchHistory"
	HistoryService_ListWatchHistory_FullMethodName    = "/history.HistoryService/ListWatchHistory"
	HistoryService_UpdateWatchProgress_FullMethodName = "/history.HistoryService/UpdateWatchProgress"
	HistoryService_DeleteWatchHistory_FullMethodName  = "/history.HistoryService/DeleteWatchHistory"
	HistoryService_GetMostWatched_FullMethodName      = "/history.HistoryService/GetMostWatched"
	HistoryService_GetRecentlyWatched_FullMethodName  = "/history.HistoryService/GetRecentlyWatched"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	RecordWatch(ctx context.Context, in *RecordWatchRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error)
	GetWatchHistory(ctx context.Context, in *GetWatchHistoryRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error)
	ListWatchHistory(ctx context.Context, in *ListWatchHistoryRequest, opts ...grpc.CallOption) (*ListWatchHistoryResponse, error)
	UpdateWatchProgress(ctx context.Context, in *UpdateWatchProgressRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error)
	DeleteWatchHistory(ctx context.Context, in *DeleteWatchHistoryRequest, opts ...grpc.CallOption) (*DeleteWatchHistoryResponse, error)
	GetMostWatched(ctx context.Context, in *GetMostWatchedRequest, opts ...grpc.CallOption) (*MostWatchedResponse, error)
	GetRecentlyWatched(ctx context.Context, in *GetRecentlyWatchedRequest, opts ...grpc.CallOption) (*ListWatchHistoryResponse, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) RecordWatch(ctx context.Context, in *RecordWatchRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_RecordWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetWatchHistory(ctx context.Context, in *GetWatchHistoryRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ListWatchHistory(ctx context.Context, in *ListWatchHistoryRequest, opts ...grpc.CallOption) (*ListWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_ListWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) UpdateWatchProgress(ctx context.Context, in *UpdateWatchProgressRequest, opts ...grpc.CallOption) (*WatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_UpdateWatchProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) DeleteWatchHistory(ctx context.Context, in *DeleteWatchHistoryRequest, opts ...grpc.CallOption) (*DeleteWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_DeleteWatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetMostWatched(ctx context.Context, in *GetMostWatchedRequest, opts ...grpc.CallOption) (*MostWatchedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MostWatchedResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetMostWatched_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetRecentlyWatched(ctx context.Context, in *GetRecentlyWatchedRequest, opts ...grpc.CallOption) (*ListWatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetRecentlyWatched_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations must embed UnimplementedHistoryServiceServer
// for forward compatibility.
type HistoryServiceServer interface {
	RecordWatch(context.Context, *RecordWatchRequest) (*WatchHistoryResponse, error)
	GetWatchHistory(context.Context, *GetWatchHistoryRequest) (*WatchHistoryResponse, error)
	ListWatchHistory(context.Context, *ListWatchHistoryRequest) (*ListWatchHistoryResponse, error)
	UpdateWatchProgress(context.Context, *UpdateWatchProgressRequest) (*WatchHistoryResponse, error)
	DeleteWatchHistory(context.Context, *DeleteWatchHistoryRequest) (*DeleteWatchHistoryResponse, error)
	GetMostWatched(context.Context, *GetMostWatchedRequest) (*MostWatchedResponse, error)
	GetRecentlyWatched(context.Context, *GetRecentlyWatchedRequest) (*ListWatchHistoryResponse, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

// UnimplementedHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) RecordWatch(context.Context, *RecordWatchRequest) (*WatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordWatch not implemented")
}
func (UnimplementedHistoryServiceServer) GetWatchHistory(context.Context, *GetWatchHistoryRequest) (*WatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchHistory not implemented")
}
func (UnimplementedHistoryServiceServer) ListWatchHistory(context.Context, *ListWatchHistoryRequest) (*ListWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchHistory not implemented")
}
func (UnimplementedHistoryServiceServer) UpdateWatchProgress(context.Context, *UpdateWatchProgressRequest) (*WatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWatchProgress not implemented")
}
func (UnimplementedHistoryServiceServer) DeleteWatchHistory(context.Context, *DeleteWatchHistoryRequest) (*DeleteWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatchHistory not implemented")
}
func (UnimplementedHistoryServiceServer) GetMostWatched(context.Context, *GetMostWatchedRequest) (*MostWatchedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMostWatched not implemented")
}
func (UnimplementedHistoryServiceServer) GetRecentlyWatched(context.Context, *GetRecentlyWatchedRequest) (*ListWatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentlyWatched not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue()                        {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_RecordWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).RecordWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_RecordWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).RecordWatch(ctx, req.(*RecordWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetWatchHistory(ctx, req.(*GetWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ListWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListWatchHistory(ctx, req.(*ListWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_UpdateWatchProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatchProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).UpdateWatchProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_UpdateWatchProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).UpdateWatchProgress(ctx, req.(*UpdateWatchProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_DeleteWatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).DeleteWatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_DeleteWatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).DeleteWatchHistory(ctx, req.(*DeleteWatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetMostWatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostWatchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetMostWatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetMostWatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetMostWatched(ctx, req.(*GetMostWatchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetRecentlyWatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentlyWatchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetRecentlyWatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetRecentlyWatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetRecentlyWatched(ctx, req.(*GetRecentlyWatchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "history.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordWatch",
			Handler:    _HistoryService_RecordWatch_Handler,
		},
		{
			MethodName: "GetWatchHistory",
			Handler:    _HistoryService_GetWatchHistory_Handler,
		},
		{
			MethodName: "ListWatchHistory",
			Handler:    _HistoryService_ListWatchHistory_Handler,
		},
		{
			MethodName: "UpdateWatchProgress",
			Handler:    _HistoryService_UpdateWatchProgress_Handler,
		},
		{
			MethodName: "DeleteWatchHistory",
			Handler:    _HistoryService_DeleteWatchHistory_Handler,
		},
		{
			MethodName: "GetMostWatched",
			Handler:    _HistoryService_GetMostWatched_Handler,
		},
		{
			MethodName: "GetRecentlyWatched",
			Handler:    _HistoryService_GetRecentlyWatched_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/history/history.proto",
}
